### ISSUE TITLE
Introduction to Snakemake for Bioinformatics

### ISSUE THREAD

**Issue by tbooth** [carpentries-incubator/proposals#101]
1. What is the topic of your lesson or lesson proposal?

Introducing the Snakemake workflow system for bioinformatics analysis.

Snakemake is a popular system for constructing computational workflows based upon the ideas of classic UNIX Makefiles. It originated in the world of bioinformatics, and this still represents the principal use of the tool. I have teaching materials from a recent course that I prepared and taught that I would like to use as the basis of a carpentries lesson. These guide the user from basic principles to constructing complex workflows, branching and pooling, measuring and optimising performance and making workflows reusable with configuration.

In particular this lesson will work alongside the workflows-nextflow lesson recently added to the carpentries incubator and being developed by my colleague @ggrimes. The two courses will share a common dataset, have matching pre-requisites, and share common goals and structure.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

The materials for my previous course are here:
https://uoe-my.sharepoint.com/:f:/g/personal/tbooth2_ed_ac_uk/EqM1pxpZvSlGgBdfynFuTucBx5mbozFZVV9J8PfPqxSo0A?e=rPeAlK
The material is currently written in office software rather than markdown or structured text.

There already exist various public teaching resources for Snakemake, notably:

* The official tutorial (https://snakemake.readthedocs.io/en/stable/tutorial/tutorial.html)

This is an excellent resource under active development, and uses a good bioinformatics-based example task. While in some ways following the principles of the Carpentries, in others it does not. There is a lack of structured exercises, and the learning goals are not clearly stated per episode. Also the lessons are not explicitly designed for live coding. I believe that the licensing on this tutorial means I should be able to draw on it for inclusion in carpentries lessons. I've not been not involved in writing this but I'll try to involve the authors in the Carpentries effort once that is underway.

* An existing introduction here in the incubator (workflows-snakemake)

This lesson includes 10 episodes and covers some of the same topics, but using a task based on Zipf's law so I don't think it is suitable to engage bioinformatics researchers. It also expects a familiarity with Python which is not a prerequisite for my course material. From the commit times on the repository (last activity from main authors in Feb 2020) I don't think this is seeing active development.

3. Do your materials conform to our [Code of Conduct][coc]?

Yes. I'll be using a slightly different dataset than for the last time I taught the course, to come into line with the NextFlow material. Everything in the teaching materials is either written by us (Ed-DASH team) or from a source that allows for re-use, and will be credited.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

I started drafting out a carpentries-type version of the course already on my local machine but I'd like to home it in the carpentries incubator on GitHub, please.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes please

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

I'll push all work to the new repo.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@tbooth
@ggrimes
@nathcmedd
@ameynert

8. Any other information you would like us to have or questions you have for us?

No, please let me know if anything above is unclear.

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal @tbooth. I have created the repository for you at https://github.com/carpentries-incubator/snakemake-novice-bioinformatics

You and your colleagues should have received an invitation to join the Maintainer Team for this lesson. Once that invitation has been accepted, you will have Maintain access to the lesson repository. I also granted you (@tbooth) Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. While working with The Carpentries lesson template, you might find [the Lesson Example](https://carpentries.github.io/lesson-example/) useful as a reference. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if anything is unclear.
