### ISSUE TITLE
FAIR in (biological) practice

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/proposals#102]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

FAIR in (biological) practice

The course is aimed at non-PI researchers in biomedicine science (PhD students, postdocs, technicians, etc.) who are interested in Open Science, FAIR principles and data management. This lesson provides the foundation for practical incorporation of Open Science and FAIR data principles into biological research data managment by showing relevant tools and best practices.

We plan this course to be practical, i.e. not why/what Open Science or FAIR are but how to plan daily work and what resources to use to be able to deliver FAIR data at the end.  

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://biordm.github.io/fair-bio-practice/
https://github.com/BioRDM/fair-bio-practice

3. Do your materials conform to our [Code of Conduct][coc]?
YES

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
YES
https://github.com/BioRDM/fair-bio-practice

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
YES

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

tzielins 
aromanowski

8. Any other information you would like us to have or questions you have for us?

We have just started work on the lessons. So there is no much content yet apart from general information and framing of the first two episodes

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by aromanowski** [comment]
Hi @tobyhodges! Could you help us create this repo? Thank you!

**Comment by tobyhodges** [comment]
Thanks for your patience. I have created a maintainer team for this lesson and added you both to it. You should be able to transfer the repository into the carpentries-incubator organisation, adding it to that Team. Please post back here to let me know when you have completed the transfer, and/or if you run into any trouble.

**Comment by tzielins** [comment]
@tobyhodges Hi Toby, I have imported the repo and added it to dev team, I hope all is at it should be. 
I have to admit I don't have much experience with working in organizations/teams setup, so please check.

**Comment by tobyhodges** [comment]
Great, thanks @tzielins. I have added some basic topics to your repository, to make sure it is listed correctly on [the page of Community Developed Lessons](https://carpentries.org/community-lessons/). 

While working with The Carpentries lesson template, you might find [the Lesson Example](https://carpentries.github.io/lesson-example/) useful as a reference. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

Lastly, you might consider opting in to chosen issues from your lesson being listed on [the Help Wanted page](https://carpentries.org/help-wanted-issues/). If you choose for your repository to be included in that listing, any issues that you label `help-wanted` will be automatically listed on there for other community members to see and (hopefully) come and help you with. You can reply here, by a new issue on your lesson repository, or contact me on Slack/email if you would like to include your lesson on that page.

I will close this issue now that the repository is set up, but I will still receive notifications so please post back here if anything is unclear.
