### ISSUE TITLE
High dimensional statistics

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/proposals#103]
1. What is the topic of your lesson or lesson proposal?

High dimensional statistics

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

**Comment by tobyhodges** [comment]
Thanks for proposing this lesson, @Alanocallaghan. Are you interested in developing a lesson on this topic, or posting here to raise the idea of the lesson only? If the former, would you like me to create a lesson repository for you to begin working on the lesson in the Incubator?

**Comment by Alanocallaghan** [comment]
A group of us based in Edinburgh will be developing a lesson on the topic, so it'd be great if you could do so

**Comment by tobyhodges** [comment]
👍 shall I use a generic name for the lesson repository e.g. `high-dimensional-stats` or can we be more specific? E.g. is the lesson aimed at a particular audience/domain such as life scientists? Will you be teaching with a particular tool/language e.g. R or Python?

**Comment by Alanocallaghan** [comment]
It will certainly be using R initially and the primary audience is a subset of life scientists, though I believe repo admins can change the slug at a later date in case we want to fine tune

**Comment by Alanocallaghan** [comment]
Thanks!

**Comment by tobyhodges** [comment]
The repository is ready at https://github.com/carpentries-incubator/high-dimensional-stats-r and I have also added you to a Maintainer Team for the lesson, which you can invite others to*.

The README of the repository includes a brief list of recommended next steps. While working with The Carpentries lesson template, you might find [the Lesson Example](https://carpentries.github.io/lesson-example/) useful as a reference. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if anything is unclear.

\*if the users you want to add are not already members of the carpentries-incubator organisation, you may need to ask me to invite them first. You can do that by tagging me in an issue, by contacting me on Slack (see above), or by sending me an email (my GitHub username at carpentries dot org).
