### ISSUE TITLE
Alternate SWC git lesson with branching/PRs

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/proposals#104]
1. What is the topic of your lesson or lesson proposal?

SWC Git Novice lesson with branches and pull requests.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes. [website](https://uw-madison-datascience.github.io/git-novice-custom/) / [repo](https://github.com/UW-Madison-DataScience/git-novice-custom)

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

Yes, I think so or they should if they don't.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@sstevens2 and @ChristinaLK are probably a good start.

8. Any other information you would like us to have or questions you have for us?

I'm not sure what the plan is for having custom variations on lessons in the incubator  but many people have been asking about and using this one so I was thinking maybe I should move it here?  Let me know what you think.

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for sharing this, @sstevens2. I am absolutely in favour of alternative lessons like this appearing in the Incubator 😄  I have added you and @ChristinaLK to a Maintainer team for this lesson, and you should be able to transfer the repository over, under the ownership of that new team. When you do so, please use the opportunity to rename the repository to something a bit more descriptive e.g. `git-novice-branching`.

Please post back here when the transfer is complete, and I will close this issue, or if you run into any trouble and I will see what I can do to help.

**Comment by sstevens2** [comment]
Ok this transfer went smoother.  Changed the name and link to the website before I moved it (because I don't have the access after) and then setup the [redirect repo](https://github.com/UW-Madison-DataScience/git-novice-custom).

[Incubator repo here](https://github.com/carpentries-incubator/git-novice-branch-pr)

Think this one can be close unless you notice any issues @tobyhodges or @ChristinaLK

**Comment by ChristinaLK** [comment]
I'm glad I checked my notifications so I knew I had been wrangled into this. ;) 
Thanks @tobyhodges !

**Comment by tobyhodges** [comment]
I have updated the permissions on the repository to give you both a more appropriate level of control @sstevens2 @ChristinaLK Closing this now that the repository is transferred and set up to go.
