### ISSUE TITLE
SWC Unix/Python/Git extension lesson

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/proposals#105]
1. What is the topic of your lesson or lesson proposal?

A lesson that ties together the unix shell, python, and git to get learners familiar with common workflows.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes. [website](https://uw-madison-datascience.github.io/python-novice-gapminder-custom/) / [repo](https://github.com/UW-Madison-DataScience/python-novice-gapminder-custom)

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

Yes, I think so.  If not we'd like them to.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@sstevens2 and @ChristinaLK would probably be good to start.

8. Any other information you would like us to have or questions you have for us?

This is another custom variation lesson though it mostly adds instead of changes from existing materials so it more easily can be an extra lesson for people to consider.

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for sharing this, @sstevens2. I have added you and @ChristinaLK to a Maintainer team for this lesson, and you should be able to transfer the repository over, under the ownership of that new team. When you do so, please use the opportunity to rename the repository to something a bit more descriptive. I think `swc-extension-shell-python-git` is a good choice, but `swc-ext-python` would also be good if you prefer something more concise 😄 

Please post back here when the transfer is complete, and I will close this issue, or if you run into any trouble and I will see what I can do to help.

**Comment by sstevens2** [comment]
So I migrated it but I should have changed the repo before.  I was thinking it might ask me in the migration process but I was wrong.  I like `swc-ext-python` well enough.  @ChristinaLK do you have thoughts about a good new name?

**Comment by sstevens2** [comment]
Let me know when you rename @tobyhodges.  I'll need to update my [redirect repo](https://github.com/UW-Madison-DataScience/python-novice-gapminder-custom)

**Comment by tobyhodges** [comment]
@sstevens2 I have updated access permissions on the repository and given you Admin privileges. So you should be able to take care of renaming the repository yourself now. Please let me know if you run into any more trouble.

**Comment by sstevens2** [comment]
Thanks @tobyhodges!  I've renamed and edited the redirects.  Should be in good shape now.  I'll go ahead and close this issue.
