### ISSUE TITLE
Introduction to R and litsearchr

### ISSUE THREAD

**Issue by ameliakallaher** [carpentries-incubator/proposals#108]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

- Introduction to R and litsearchr

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

- (https://ameliakallaher.github.io/lc-litsearchr)/ 

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

- Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

- Yes

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

- Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

- ameliakallaher
- elizagrames
- rootsandberries

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to the Incubator, @ameliakallaher. I've invited you and your collaborators to the carpentries-incubator organization on GitHub, in the _litsearchr-maintainers_ team. After accepting that invitation, you should be able to transfer the repository into the carpentries-incubator organisation. Please post back here when the transfer is complete, and/or to ask any questions you have about the process.

A couple of points to mention at this stage:
1. I notice that this lesson is using the Library Carpentry template. Is your intention to eventually submit this as an additional lesson to the Library Carpentry program?
2. To make ownership clear for our community-developed lessons, we would prefer all lessons in the Incubator to use the Incubator version of the lesson template (see [the Introduction to Conda lesson, for example](https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/)). I would be happy to submit a Pull Request to make this change in the lesson configuration, after the lesson has been transferred. If/when the lesson moves out of the Incubator (e.g. into the Library Carpentry organisation), the configuration can be updated again to provide the appropriate lesson template.

**Comment by ameliakallaher** [comment]
Great. Thank you for sharing the next steps.

Yes, we would like to submit the lesson to the Library Carpentry program. The information I have from their website is “Propose your lesson for the incubator by making a pull request (PR) against the Library Carpentry website, adding a link to your lesson repository as an alpha lesson.” By transferring the lesson to the Incubator are we moving towards that step?

Also, I’m fine with the lesson template being changed to fit the Incubator template version for consistency.

Best,

Amelia Kallaher
Applied Social Science Librarian at the Albert R. Mann Library
Cornell University
***@***.******@***.***> | 607-255-8869

**Comment by tobyhodges** [comment]
Thanks for responding so quickly, @ameliakallaher. I will alert the Library Carpentry Curriculum Advisors to the existence of your lesson at their next meeting.

You may transfer the repository over to carpentries-incubator whenever you are ready, and I will open a Pull Request to update the lesson template.

**Comment by tobyhodges** [comment]
@ameliakallaher I am going to close this issue now that the lesson transfer has been completed. As discussed, I opened [a pull request to adjust the lesson styling for the Incubator](https://github.com/carpentries-incubator/lc-litsearchr/pull/2) - it contains a lot of commits to include the most recent updates to the lesson template, but I believe it is safe to merge. Please tag me or reach out on The Carpentries Slack workspace if you have any questions or need any help.
