### ISSUE TITLE
Foundational Computer Skills

### ISSUE THREAD

**Issue by annajiat** [carpentries-incubator/proposals#109]
1. What is the topic of your lesson or lesson proposal?
Foundational Computer Skills

2. Do you already have a draft of your lesson? 
No

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
yes

8. Any other information you would like us to have or questions you have for us?

Workshops may welcome participants from mixed backgrounds. Some
learners may need help to be able to:
-download the data files
-put the data files in proper locations
-how to unzip the files
-how to move the downloaded files from the downloads folder without
having to re-download
-locate home directory/folder
-differentiate that opening a zip file may not be the same as unzipping it
-remove the duplicate folder created by some unzipping program e.g.
folder.zip -> folder\folder\file.txt
-etc.

We can take some inspirations from:
https://wikieducator.org/Foundational_Computer_Skills

Some of these are often solved during  the setup or pre-workshop
sessions. However, we often observe that some learners who need the
help sometimes cannot make it to the pre-workshop setup sessions.
Later, helpers may get overwhelmed and/or multiple breakout sessions
are needed to troubleshoot as the steps might vary due to the
operating systems.

Additionally, some lessons emphasize on downloading files beforehand
whereas some other lessons take the approach of downloading the files
as we go through different episodes.

This curriculum is for Foundational Computer skills so that
-learners without the prior backgrounds can look up
-helpers can refer learners to those materials
-organizers can include that as part of the announcements.

**Comment by tobyhodges** [comment]
Thanks for putting in this proposal @annajiat. I have created the repository for the lesson at https://github.com/carpentries-incubator/foundational-computer-skills and added you as a maintainer. You also have the power to add other collaborators to the Maintainer team for the lesson, if and when you would like to do so.

I know this is not your first time working with a lesson repository in The Carpentries Incubator so I will keep my wrap-up quite brief here. The repository README file includes some suggested first steps to take towards completing the setup of the repository. You can also reply here if you have any questions or run into any difficulty with the repository. I will close this issue now that the repository has been set up, but will still be notified if and when you continue to post here.
