### ISSUE TITLE
FAIR for leaders

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/proposals#111]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Leading researchers must become conversant with the Open Science ethos, the Reproducible Research movement, and FAIR (Findable Accessible Interoperable Reusable) principles to recognize or evaluate them in their peers, to mentor their team members and to benefit from efficient data management. This one-day workshop is aimed at established PIs and institutional leaders who set policy and drive changes. It will set the foundations of Open Science, FAIR principles and what they mean for biomedical research practices. The participants will be able to steer the adoption of good data management within their organisation and teams for the improvement of both data re-use and work efficiency. 

This lesson is meant to be complementary to https://carpentries-incubator.github.io/fair-bio-practice/ 
targetting the senior figures with stronger focus on why/when rather than with which tools.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

I have created the repository in the carpentries incubator alread. I hope it is OK.

https://github.com/carpentries-incubator/fair-for-leaders

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tzielins** [comment]
@tobyhodges I have imported the lesson template into the carpentries incubator and tried to set it up similarly to the
fair-bio-practice you did for us.

I hope it is OK, I was just trying to save time of carpentries team.

**Comment by tobyhodges** [comment]
Thanks for the message, and for the lesson proposal @tzielins. Everything looks good with the repository - and I am grateful for your concern about saving us time! We discussed this at the Curriculum Team meeting yesterday and concluded that we are happy for existing members of the carpentries-incubator GitHub organisation to create repositories for themselves like this, as long as they open an issue on this repository to tell us about it (as you have done here). For book-keeping purposes, we want to try to maintain a setup where every Incubator repository has a corresponding issue in this repository.

Everything seems to be taken care of here, so I am going to close the issue now. Thanks again!
