### ISSUE TITLE
Introduction to Data Science for Biomedical Scientists

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/proposals#112]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
- Introduction to Data Science for Biomedical Scientists: Turing-Crick Partnership Project

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
- The project is in the preparation phase, here is the project proposal: https://github.com/alan-turing-institute/data-training-for-bioscience/blob/main/proposal/2021-06-ASG-proposal.md. A project charter will be added to the repository soon.

3. Do your materials conform to our [Code of Conduct][coc]?
- Yes. The CoC will be enforced under the project's CoC as listed on the repository: https://github.com/alan-turing-institute/data-training-for-bioscience.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
- No. The materials are yet to be developed but they will use The Carpentries templates.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
- No.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
- Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
- @malvikasharan (more members will be added soon)

8. Any other information you would like us to have or questions you have for us?
- How can we involve someone from The Carpentries in the planning meeting to ensure fair collaboration?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hey @malvikasharan! Thanks for submitting this lesson to The Carpentries Incubator.

I can go ahead and create a repository for this lesson in the Incubator, which you can start working on when your team begin developing the lesson, if you like? Or will you begin working on it elsewhere (e.g. in the repository you linked to above), and then transfer the repository into the Incubator?

**Comment by malvikasharan** [comment]
Thanks, @tobyhodges for the quick response. 😇

Please create a repository for us so that we get folks involved in this project to directly contribute to the repository. It will also help us avoid any redundancy or coordination.
Can you please add @LydiaFrance to the repo as well?

**Comment by tobyhodges** [comment]
I have created the repository for you at https://github.com/carpentries-incubator/datasci-biomedical-scientists and invited you to join it as an administrator. You and @LydiaFrance should also have received an invitation to join a `data-training-for-bioscience-maintainers` Team, which will have Maintain access to the repository. Please accept both invitations, @malvikasharan, and you will then have full ownership of the repository.

The README of the repository includes a brief list of recommended next steps. While working with The Carpentries lesson template, you and your colleagues might find [the Lesson Example](https://carpentries.github.io/lesson-example/) useful as a reference. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions.
