### ISSUE TITLE
Introduction to Zotero

### ISSUE THREAD

**Issue by pallykkja** [carpentries-incubator/proposals#124]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal? 
I want to teach how to use Zotero for PDF management and perform advanced search/sorting/organising of fulltext sources. https://www.zotero.org/blog/zotero-6/ 

3. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link. No draft right now but it goes like this: 1) Install and setup on Mac, Windows, Linux, Chromebook and iOS platform 2) Import just two references and cite them 3) Import PDF from the computers, create references from scratch, clean up imports, deduplicate 4) Learn to annotate, annotate within a group or learning partner (exercise) 5) Make a literature overview through searching many databases 6) Learn how to perform advanced search/sorting/organising 7) How to use Zotero to avoid risks of plagiarism effectively 8) Set up Zotero with Markdown editors, Google Docs, Microsoft Word, Libre Office 9) How to create audio files of text and use mobile phone to play it from Zotero 10) Install and use OCR inside Zotero https://github.com/UB-Mannheim/zotero-ocr/releases/tag/0.5.0 11) 

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

4. Do your materials conform to our [Code of Conduct][coc]? Yes.

5. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template). No.

6. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator? Yes please.

7. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository. Yes.

8. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. Yes.

9. Any other information you would like us to have or questions you have for us? I know that there are many advanced users of Zotero out there, so I am willing to cooperate with anyone.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by MCMaurer** [comment]
Thanks for this lesson proposal @pallykkja! I have created the repository for you at https://github.com/carpentries-incubator/zotero-intro.

You and your colleagues should have received an invitation to join the Maintainer Team for this lesson. Once that invitation has been accepted, you will have Maintain access to the lesson repository. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. While working with The Carpentries lesson template, you might find [the Lesson Example](https://carpentries.github.io/lesson-example/) useful as a reference. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!

**Comment by pallykkja** [comment]
Thank you so much, it is so important to get in touch with others for the teaching design. Now I will go through the lessons, and try to apply what I have learned about teaching in carpentry.
