### ISSUE TITLE
Multi-dimensional biodiversity data management and analysis

### ISSUE THREAD

**Issue by isaacovercast** [carpentries-incubator/proposals#125]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Broadly: Multi-dimensional biodiversity data management and analysis

This proposed lesson will focus on how to prepare and use datasets following the data standards used in ecology and evolution (Ecological Metadata Language, DarwinCore, HumboldtCore) and also highlight the many unsolved challenges in managing, analyzing, and quantitatively studying heterogeneous biodiversity data.

We envision this as a 2-day workshop to leverage and build upon the existing ecology-based Data Carpentry curriculum.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

We have a very rough draft, but we would like to start developing this in earnest at the soonest.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

No the materials aren't on github, but we would like them to be, and we definitely intend to use the carpentries lesson template.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes please.

7. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

8. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

9. Any other information you would like us to have or questions you have for us?

Thanks for all your great work on this awesome community resource!

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by MCMaurer** [comment]
Thanks for this lesson proposal @isaacovercast! I have created the repository for you at https://github.com/carpentries-incubator/multidimensional-biodiversity-data.

You should have received an invitation to join the Maintainer Team for this lesson. Once that invitation has been accepted, you will have Maintain access to the lesson repository, and you can add any collaborators to this team as well. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. While working with The Carpentries lesson template, you might find [the Lesson Example](https://carpentries.github.io/lesson-example/) useful as a reference. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions.
