### ISSUE TITLE
R Packages

### ISSUE THREAD

**Issue by PabRod** [carpentries-incubator/proposals#126]
# Lesson Proposal: R Packages

### What is the topic of your lesson or lesson proposal?

How and why build your own R packages.

### Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

The materials are available [here](https://github.com/esciencecenter-digital-skills/lesson-R-packaging).

### Do your materials conform to our [Code of Conduct][coc]?

Yes.

## Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes to all.

### Would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes (as long as the issues can also be transferred).

### List the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

- [PabRod](https://github.com/PabRod)
- [liekelotte](https://github.com/liekelotte)
- [bvreede](https://github.com/bvreede)

### Any other information you would like us to have or questions you have for us?

1. The status of the materials is alpha. We already used them once during a 3-day course, and at the moment we are actively working on implementing the students' (and our own) feedback.
2. Our pilot course raised less attention than we expected. We think this may be due to the name we used for it: R Packages. We are considering alternatives that highlight the use of packaging for researchers. Something in the lines of: "Reproducible research with R".

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by MCMaurer** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @PabRod!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the carpentries-incubator organisation on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into carpentries-incubator, via the repository Settings. It will retain all the current Issues in the repository, no worries on that! When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given “Maintain” privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by PabRod** [comment]
Thanks, @MCMaurer.

According to GitHub documentation, the following is true for the issues:

> When a repository is transferred between two personal accounts, issue assignments are left intact. **When you transfer a repository from a personal account to an organization, issues assigned to members in the organization remain intact, and all other issue assignees are cleared**. Only owners in the organization are allowed to create new issue assignments. When you transfer a repository from an organization to a personal account, only issues assigned to the repository's owner are kept, and all other issue assignees are removed.

So I'll wait until my collaborators @bvreede and @liekelotte receive and accept their invitations.

Have a nice day!

**Comment by MCMaurer** [comment]
Hi @PabRod, I've gone ahead and added them both to the lesson developers team, which means they will also be added to the Incubator organization. Thanks for the heads up regarding the Issue assignments, I'll note that in our documentation for how to transfer repositories in the future!

**Comment by PabRod** [comment]
I've just transferred it. Shall we close this issue, @MCMaurer?

**Comment by MCMaurer** [comment]
Sounds great @PabRod, thanks for doing the transfer! Feel free to reach out if you run into any issues.
