### ISSUE TITLE
Introduction to Reproducible Publications with RStudio

### ISSUE THREAD

**Issue by rcurty** [carpentries-incubator/proposals#130]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Participants will build on their research and analytical skills with R Studio by learning how to create reproducible documents that combine code, analysis and narrative. RStudio makes it possible to work on a complete research project in a more efficient, integrated and organized manner: from data upload, cleaning, and analysis, to writing and styling a manuscript in R Markdown. It allows users to add code, figures, citations, and bibliography, as well as to generate outputs in various formats (e.g., html, pdf, doc). Rstudio also connects with Git and Github and learners will have a chance to experiment with this integration and understand its advantages for collaboration and version control. This workshop will involve lectures and demos alternating with hands-on exercises and challenges, so by the end of the workshop, learners will have “authored” a reproducible paper of your own with the data and narrative we provide.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes, the curriculum is fully developed and was already taught twice (https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/).

3. Do your materials conform to our [Code of Conduct][coc]?
Yes, our materials were developed with The Carpentries conduct of conduct in mind. We pledge contributors and maintainers of this project to follow it and include in our curriculum that instances of abusive, harassing, or otherwise unacceptable behavior may be reported by following our reporting guidelines.  

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
Yes, we developed the curriculum following The Carpentries lesson template and all materials are available on GitHub.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator? 
N/A

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
Yes. 

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
Renata Curty (rcurty)
Torin White (torwhite)
Ian Lessing (ilessing)
kristi Liu (kristi-sara)
Amanda Ho (apandas)

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by MCMaurer** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @rcurty!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the carpentries-incubator organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into carpentries-incubator, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given “Maintain” privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by rcurty** [comment]
Hello @MCMaurer:

We have completed the transfer process.
Our workshop has a separate repo that houses the [project example](https://github.com/UCSBCarpentry/Reproducible-rmd). Learners are required to download it in ep. 5 to follow along. We are unsure whether we should transfer this repo to the incubator too. Could you please advise?

Thanks!
@rcurty

**Comment by MCMaurer** [comment]
Hi @rcurty, I think it is probably best to transfer it as well. If you'd like to do that, I will give you administrative access and give the team Maintain access, just like with the lesson repo!

**Comment by rcurty** [comment]
Hello @MCMaurer, I am afraid that the two separate entries in the incubator might confuse potential contributors. Any ideas how we can make the relationship between the two repos more evident to the community in the incubator listing?

**Comment by MCMaurer** [comment]
I think changing the name of the example repo might help, maybe something like `Reproducible-Publications-with-RStudio-Example` would make it clear enough. I think making explicit references in the READMEs of each repo would help as well. I think most potential contributors will be able to distinguish between the two if you delineate them in these ways. I think having something like "this is NOT the lesson repository" at the top of the example README would be particularly useful.

**Comment by rcurty** [comment]
Done. Please let me know when I can transfer it. Thanks!

**Comment by rcurty** [comment]
@MCMaurer our team is ready to transfer the other repo. Could you please grant me admin access? Thanks!

**Comment by tobyhodges** [comment]
@rcurty I have granted the @carpentries-incubator/reproducible_publications_rstudio_developers team _Maintain_ access to the example repository, and have added you as _Admin_ on the repository. A couple pieces on information to help you get settled into the Incubator:

1. We removed the "lesson" topic from the repository. We use this topic to list lessons on our websites, and I would like to avoid including "supporting material" repositories such as this from those lesson listings.
2. @MCMaurer will be away for a while, so please tag me on GitHub or reach out on The Carpentries Slack workspace if you need help with anything.
3. If you would like to raise the visibility of your lesson across the community, I encourage you to [submit the lesson for the Incubator Lesson Spotlight series](https://forms.gle/uC36ZvQzWwDFWUyE6), where it will be featured in our blog and newsletter - [read more about it in the community handbook](https://docs.carpentries.org/topic_folders/lesson_development/spotlight.html).

Now that both transfers are complete, I will close this issue. I will still receive notifications though, so please reply here or tag me in an issue on the repository if you need further help with anything.
