### ISSUE TITLE
Harvesting Twitter Data with twarc

### ISSUE THREAD

**Issue by jonjab** [carpentries-incubator/proposals#131]
1. What is the topic of your lesson or lesson proposal?
Our lesson builds on Jupyter / Python skills and introduces the use of the Twitter v2 API and
[Documenting the Now's twarc](https://twarc-project.readthedocs.io/en/latest/) tool for harvesting
and analyzing tweets.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes. https://ucsbcarpentry.github.io/twitter-with-twarc/index.html

3. Do your materials conform to our [Code of Conduct][coc]?
Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
Yes

6. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

7. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
Yes

8. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
jonjab, kristi-sara, ameliameyer, apandas, thaophan1, jinxiang2000

9. Any other information you would like us to have or questions you have for us?
We have consent from Bergis Jules to harvest his Twitter timeline and use his identity in the lesson.

We love you!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @jonjab, and for your kind note at the end of the submission 😄 The lesson looks very cool, and I'm sure it will be interesting to many other members of the community. It is also good to hear that you have teh consent of the Twitter user to use his data and details in the lesson.

You should have received an invitation to join a Team of maintainers for the lesson, as part of the _carpentries-incubator_ organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into _carpentries-incubator_, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given “Maintain” privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by tobyhodges** [comment]
@jonjab thank you for transferring [the lesson repository](https://github.com/carpentries-incubator/twitter-with-twarc/). You and your collaborators have access, so I am going to close this issue. Please tag me on GitHub or reach out via The Carpentries Slack workspace if you have any questions or need help with anything.
