### ISSUE TITLE
Lesson Proposal: Introduction to Data Visualization

### ISSUE THREAD

**Issue by jbkieffer** [carpentries-incubator/proposals#132]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

The lesson introduces data visualization from the ground up. Communication and message are introduced as the foundation of any chart. After a simplified overview of graphics theory, learners practice identifying messages of existing charts and creating charts to communicate messages.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes; this lesson is being developed as part of the Lesson Development Workshop Pilot. Lesson materials are at [https://github.com/jbkieffer/intro-data-viz](https://github.com/jbkieffer/intro-data-viz/issues); rendered at [https://jbkieffer.github.io/intro-data-viz/index.html](https://jbkieffer.github.io/intro-data-viz/index.html)

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

4. Do your materials conform to our [Code of Conduct][coc]?

Yes

5. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes

6. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

7. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes
8. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

9. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by jbkieffer** [comment]
All done on my end. I will watch for becoming admin on the repository so we can continue development. No worries if this doesn't happen before the end of CarpentryCon.

**Comment by tobyhodges** [comment]
Thanks @jbkieffer I have made you an Admin and invited your two collaborators to join the Maintainer Team as well. As repository Admin, you can give them Maintain access individually but, if they join the team they will gain Maintain access that way regardless.

I will close this issue now but please post back here or tag me in an issue on the lesson repository if you need help or have any questions.
