### ISSUE TITLE
ENCODE website usage

### ISSUE THREAD

**Issue by meenakshikagda** [carpentries-incubator/proposals#137]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal? Ans: teaching how to use the ENCODE website https://www.encodeproject.org, which is a huge collection of biologically important datasets.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
No
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for this lesson proposal, @meenakshikagda! Would you like me to create a new lesson repository for you to begin building this lesson in the Incubator? If so, what would you like me to call it? Perhaps `encode-novice`?

Also, if you would like me to create a repository for you, would you prefer to use [the old lesson template](https://carpentries.github.io/lesson-example/), or the new infrastructure, [The Carpentries Workbench](https://carpentries.github.io/sandpaper-docs/) (currently entering [beta testing](https://carpentries.org/blog/2022/08/dovetail-006/))? 

In case you are not familiar with either: my summary would be that the old template will look similar to existing Carpentries lessons and you would have more examples of other lesson projects to draw from. The Workbench is newer, with fewer examples and the potential for some bugs as the infrastructure matures, but has a simpler syntax and is much easier to install on your local system.

**Comment by meenakshikagda** [comment]
Hi Toby,

I think let's call it encode-data-exploration. I am happy to try the newer infrastructure. Could you please help me get started?

Thanks,
Meenakshi

**Comment by tobyhodges** [comment]
Thanks @meenakshikagda, I have created the repository for you at https://github.com/carpentries-incubator/encode-data-exploration

You should have received an invitation to join the Maintainer Team for this lesson. Once that invitation has been accepted, the team will have Maintain access to the lesson repository. This means you can add more people to that team, if you want to include other collaborators on the lesson project. I granted you (@meenakshikagda) Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. While working with The Carpentries Workbench, you might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) useful as a reference. If you have questions about the Workbench after reading that guide, @zkamvar is the best person to ask. We will also appreciate any feedback you have about the Workbench over at https://github.com/carpentries/workbench/discussions

[The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and [the Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions.

**Comment by meenakshikagda** [comment]
Hi Toby,

Thanks a lot. I will look through the resources you have mentioned above and will ask any questions I have. 

I am however unable to join the slack channel. I am getting an error message. Could someone help me get that part resolved?

Thanks,
Meenakshi

**Comment by tobyhodges** [comment]
Hi @meenakshikagda sorry for the delay in responding. You may need to join our Slack workspace first, before you can join the lesson-dev channel. You can join the workspace by following this link: https://swc-slack-invite.herokuapp.com/

**Comment by meenakshikagda** [comment]
Thank you Toby! I could join slack by following the link you provided...
