### ISSUE TITLE
Introduction to reinforcement learning in Python

### ISSUE THREAD

**Issue by tompollard** [carpentries-incubator/proposals#147]
Hi all, if possible I would like to create a new lesson on "Reinforcement learning in Python" to supplement some existing machine learning lessons that we are teaching for https://edcarp.github.io/Ed-DaSH/:

- Introduction to machine learning: https://carpentries-incubator.github.io/machine-learning-novice-python/
- Neural networks: https://carpentries-incubator.github.io/machine-learning-neural-python/
- Tree models: https://carpentries-incubator.github.io/machine-learning-trees-python/
- Responsible machine learning: https://carpentries-incubator.github.io/machine-learning-responsible-python/

1. What is the topic of your lesson or lesson proposal?

The lesson would provide an introduction to [reinforcement learning](https://en.wikipedia.org/wiki/Reinforcement_learning), a type of machine learning where models learn by interacting with their environment.

3. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Not yet, but I am in discussion with various people who are already teaching reinforcement learning, so the plan is to adapt existing materials.

(If you answered "No" to question 2, you can skip to question 5. Thank you for your lesson idea!)

5. Do your materials conform to our [Code of Conduct][coc]?

Yes, we will endeavor to follow the Code of Conduct.  

7. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template] or [The Carpentries Workbench][workbench]? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

No.

9. If you answered "No" to question 2 or either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes please! Ideally "machine-learning-reinforcement-python".

11. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

N/A

13. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@tompollard, Giacomo Peru.

15. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles
[workbench]: https://carpentries.github.io/workbench/

**Comment by MCMaurer** [comment]
Thanks for this lesson proposal @tompollard . I have created the repository for you [here
](https://github.com/carpentries-incubator/machine-learning-reinforcement-python).

You and your colleagues should have received an invitation to join the Maintainer Team for this lesson. Once that invitation has been accepted, you will have Maintain access to the lesson repository. I also granted you (@tompollard ) Admin access to the repository so you have full control. I should note that I wasn't able to add Giacomo, but you should be able to add them to the Maintainer Team yourself.

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions.

**Comment by tompollard** [comment]
Thanks @MCMaurer, I appreciate your help!
