### ISSUE TITLE
[Proposal]: Fundamentals of scientific metadata: why context matters

### ISSUE THREAD

**Issue by SilkeGerlich** [carpentries-incubator/proposals#150]
### 1. Lesson Topic

Introduction to the fundamentals of scientific metadata

### 2. Draft materials

https://notes.desy.de/EGDSAA_kS326xIv8F_b8XA?view

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 6. Collaborators

@strupp-a
@hofmannv
@ssandfeld
@apirogov

### 7. Info/Questions

Lesson abstract:

This course is an entry-level introduction to the fundamentals of scientific metadata for PhD students, early-career researchers and Postdocs. In this course we will look at the intricate relationship between (digital) research data, metadata and knowledge, discuss why metadata is critical in today’s research, as well as explain some of the technologies and concepts related to structured machine-readable metadata.

Have you ever struggled to make sense of scientific data provided by a collaborator - or even understanding your own data 5 months after publication? Do you see difficulties in meeting the data description requirements of your funding agency? Do you want your data to have lasting value, but don’t know how to ensure that?

Precise and structured description of research data is key for scientific exchange and progress - and also for the recognition of your effort in data collection. The solution: make your data findable, accessible, interoperable and reusable by describing them with metadata.

You will learn:

- about the differences between and the importance of data & metadata-
- to annotate your research data with structured metadata
- to find and evaluate a suitable metadata framework and data repository
- to use basic Markdown / JSON / XML
- which tools are already available to level up your metadata annotation game
- why structured metadata is important and how it can increase your scientific visibility

**Comment by SilkeGerlich** [comment]
Thank you so much for your feedback, @tobyhodges! 

We have discussed and reviewed both options and decided on *The Carpentries Workbench*. The future metadata schema implementation certainly supported our decision ;).

We are looking forward to fill the repo ones created.

**Comment by tobyhodges** [comment]
Thanks @SilkeGerlich I have created the new lesson repository for you at https://github.com/carpentries-incubator/scientific-metadata, and invited you and the collaborators you listed to join it.

As a next step, I recommend that you explore [the documentation for the lesson infrastructure](https://carpentries.github.io/sandpaper-docs/introduction.html). This includes information about how you can edit the blank template lesson in your new repository. You may also find our resources about lesson design and collaborative development helpful:

- [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) 
- [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) - this includes some mention of the old lesson infrastructure, i.e. not the Workbench

Finally, you will also find [guidance and resources for lesson development in our community handbook](https://docs.carpentries.org/topic_folders/lesson_development/). 

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions.
