### ISSUE TITLE
netlify GitHub app "suspended"

### ISSUE THREAD

**Issue by mr-c** [carpentries-incubator/proposals#152]
Hello,

We use netlify to preview contributions to https://github.com/carpentries-incubator/cwl-novice-tutorial/

However it doesn't work anymore and https://github.com/carpentries-incubator/cwl-novice-tutorial/settings/installations lists it as "suspended". I don't have permission to change that.

>  You do not have permission to modify this app on carpentries-incubator. Please contact an Organization Owner.  

![image](https://user-images.githubusercontent.com/1330696/206151808-cb20aafc-65e5-4a9e-ad23-7288fdfbdb7e.png)

Can this be fixed? If we should use a different service to render PRs, please let me know.

Thanks!

**Comment by tobyhodges** [comment]
The app has been unsuspended, and we have now published [a brief policy for activation of GitHub Apps](https://carpentries-incubator.org/apps-policy.html) on Incubator lesson repositories. Sorry for the relatively long period where you did not have access to the service.
