### ISSUE TITLE
FAIR Data Management for Long-term Agricultural Experiments

### ISSUE THREAD

**Issue by richardostler** [carpentries-incubator/proposals#153]
I am co-investigator on a grant to develop data management and analysis training for long-term agricultural experiments. I am leading on the data management part of the training which will cover an Introduction to FAIR, metadata, data organisation (with Excel) and publishing. Some of this content will already be covered in other Carpentry lessons (for example [FAIR in Biopractice](https://carpentries-incubator.github.io/fair-bio-practice/), but not all of this content is relevant and it has some specific domain gaps. This course will therefore be tailored to this specific research community. 

thanks,

Richard

**Comment by tobyhodges** [comment]
Thanks for opening this issue, @richardostler. The course you describe sounds very interesting and will definitely meet a need. If you want to develop a new lesson for the content you cannot cover from other existing lessons, please [open a new lesson proposal issue](https://github.com/carpentries-incubator/proposals/issues/new?assignees=tobyhodges&labels=proposal&template=lesson_proposal.yml&title=%5BProposal%5D%3A+) and fill in the questions in the form. That information will help me get you started.

**Comment by richardostler** [comment]
Thanks @tobyhodges, and new lesson proposal issue submitted.
