### ISSUE TITLE
[Proposal]: FAIR Data Management for Long-term Agricultural Experiments

### ISSUE THREAD

**Issue by richardostler** [carpentries-incubator/proposals#154]
### 1. Lesson Topic

FAIR Data Management for Long-term Agricultural Experiments

### 2. Draft materials

Yes but only drafted as an MS Word document

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 7. Info/Questions

This training is being developed as part of a UKRI-GCRF/Newton consolation account award to deliver one-off training on long-term agricultural experiments for data management, experiment design and analysis. I am preparing the data management component and would like to make the materials available, following the carpentries model, as I believe they will be of benefit to the wider community.

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal @richardostler. I would be happy to create a repository for you to work on this lesson in the Incubator. There are currently two options we offer for the template on which the lesson will be built: would you prefer to use [the old lesson template](https://carpentries.github.io/lesson-example/), or the new infrastructure, [The Carpentries Workbench](https://carpentries.github.io/sandpaper-docs/), which is currently going through beta testing?

In case you are not familiar with either: my summary is that the old template will look similar to existing Carpentries lessons and you would have more examples of other lesson projects to draw from. The Workbench is newer, with fewer examples and the potential for some bugs as the infrastructure matures, but has a simpler syntax, results in a more accessible lesson website, and is much easier to install on a local system. 

My recommendation is to use the new infrastructure (the Workbench) but it is really up to you - it is possible, and quite easy, to switch to the new infrastructure later.

**Comment by richardostler** [comment]
Hi @tobyhodges, I'm happy to give the new Carpentries Workbench a go.

**Comment by tobyhodges** [comment]
Thanks @richardostler, I have created the repository for you at https://github.com/carpentries-incubator/fair-data-management-agriculture

You should have received an invitation to join the Maintainer Team for this lesson. I granted you Admin access to the repository so you have full control, and you can add more members to the maintainer team if and when you gain collaborators on the project.

[The Workbench documentation](https://carpentries.github.io/sandpaper-docs/introduction.html) provides more information about how you can work with the lesson infrastructure. As you might remember from the Study Groups round, [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) provides an overview of the approach we recommend to lesson design and development, and the new [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) also provides some guidance to both the lesson design process and the Workbench template. Please post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

You might already be subscribed, but here's a reminder that you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions.
