### ISSUE TITLE
[Proposal]: Statistical and Probabilistic Programming

### ISSUE THREAD

**Issue by velait** [carpentries-incubator/proposals#158]
### 1. Lesson Topic

Statistical and probabilistic programming

### 3. Requirements for existing materials

- [x] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [x] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [x] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal, @velait. I will be happy to create a new repository for you to begin working on. Before I do, can you tell me if you will be using R as the main programming language for examples etc in the lesson? If so, I will create a repository set up to build from R Markdown source files. If not, I will provide a repository set up for standard Markdown source.

**Comment by velait** [comment]
Hi!

Thanks for the reply!

Yes, we are using R as the language for the material.

Best,
Ville Laitinen
________________________________________
Lähettäjä: Toby Hodges ***@***.***>
Lähetetty: tiistai 23. toukokuuta 2023 12.32.45
Vastaanottaja: carpentries-incubator/proposals
Kopio: Ville Laitinen; Mention
Aihe: Re: [carpentries-incubator/proposals] [Proposal]: Statistical and Probabilistic Programming (Issue #158)

Thanks for this lesson proposal, @velait<https://github.com/velait>. I will be happy to create a new repository for you to begin working on. Before I do, can you tell me if you will be using R as the main programming language for examples etc in the lesson? If so, I will create a repository set up to build from R Markdown source files. If not, I will provide a repository set up for standard Markdown source.

**Comment by tobyhodges** [comment]
Thanks for the quick response, @velait.

I have created the repository for you at https://github.com/carpentries-incubator/statistical-probabilistic-programming-r.

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriuclum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!
