### ISSUE TITLE
Lesson Idea: Business Analytics in R

### ISSUE THREAD

**Issue by kmbuki** [carpentries-incubator/proposals#159]
### 1. Lesson Topic

Business Analytics in R - Nearly every aspect of business is affected by data analytics on the modern world. For businesses to capitalize on data analytics, they need staff who understand the business analytic workflow and use modern tools to prepare business data for analytic purposes. R can be used for cleaning, transforming, aggregating, and reshaping data. I propose a Business Analytics Workshop that will help business users to integrate R in their business analytic workflow. The lessons will be aimed at giving learners the confidence, knowledge and techniques required to perform analytical activities in R in a business analytic workflow.

### 3. Requirements for existing materials

- [ ] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [ ] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal @kmbuki.

I have created the repository for you at https://github.com/carpentries-incubator/business-analytics-r.

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriuclum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!
