### ISSUE TITLE
Line_list_management

### ISSUE THREAD

**Issue by DHatziioanou** [carpentries-incubator/proposals#162]
An introduction to managing diagnostic and clinical data to manage research-compatible line lists

**Comment by tobyhodges** [comment]
Thanks for opening this issue, @DHatziioanou.

Are you proposing this topic as a new lesson for the Incubator? If so, would you like me to create a new lesson repository for you to get started on it?

**Comment by DHatziioanou** [comment]
Hi Toby,

Yes I am working on putting together a new lesson. My draft is currently recorded in a word document and I would like a new lesson repository to transition to working on it from here. Is that alright?

Many thanks,
Diane

**Comment by ErinBecker** [comment]
Hi @DHatziioanou - sorry for the delayed response. I'm working on getting a lesson repository set up for you. Will let you know as soon as its available.

**Comment by ErinBecker** [comment]
Thanks for this lesson proposal @DHatziioanou.

I have created the repository for you at https://github.com/carpentries-incubator/line-list-management.

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriuclum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!

**Comment by DHatziioanou** [comment]
Thank you very much Erin, that's great!

Best wishes,
Diane 




Jul 27, 2023, 19:52 by ***@***.***:
