### ISSUE TITLE
[Proposal]: Indigenous Data Sovereignty

### ISSUE THREAD

**Issue by AndrewMartinez22** [carpentries-incubator/proposals#164]
### 1. Lesson Topic

Indigenous Data Sovereignty

### 3. Requirements for existing materials

- [ ] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 6. Collaborators

@AndrewMartinez22
@jewelcummins 
@joslynnlee
@ktsosie

### 7. Info/Questions

Greetings Carpentries Team, 

We are excited to get this moving forward with you all. Jewel and I previously spoke with Erin and Alycia about setting up a separate repository for this work while we are in draft mode. I also see that I have an option to create a repository through my own account, so I'm not sure if I should go that route. I will wait to hear back. 

Lesson Background:
Introduces the concepts and framework of Indigenous Data Sovereignty and Governance. Guided through an Indigenous lens, participants will learn foundational principles and tools for working in relation with Indigenous Peoples and Indigenous data. Participants will understand how data is applied to strengthen Indigenous governance and how that data is governed. 

Episode Breakdown:
Part 1: Episodes 1-5 (Thematic questions)
	Episode 1: Introduction to Indigenous Peoples 
	Episode 2: Indigenous Peoples as Data Scientists  
	Episode 3: Indigenous Data Sovereignty
Episode 4: Data for Indigenous Governance
	Episode 5: Governance of Indigenous Peoples’ Data 

Part 2: Episodes 6-7 (new or same set of thematic questions)
	Episode 6: CARE Principles for Indigenous Data Governance
	Episode 7: Indigenous Peoples’ Data in Open Contexts

Part 3: Tools and Use Cases (more detailed and in-depth; i.e. JSON files with records)

We have more details on this that we shared with Erin and Alycia, I just need to know they best way to upload it. 

Thank you,
Andrew

**Comment by tobyhodges** [comment]
Hi @AndrewMartinez22 I'm very excited to see you proposing this.

Would you like to build all of these three parts into a single lesson, or would you prefer that I open three new lesson repositories for the individual parts, which you can develop together as a curriculum? (See [Data Carpentry: Social Sciences](https://datacarpentry.org/socialsci-workshop/) and [the Metagenomics curriculum](https://carpentries-lab.github.io/metagenomics-workshop/) recently accepted to The Carpentries Lab as examples of a multi-lesson curriculum.)

**Comment by AndrewMartinez22** [comment]
Greeting @tobyhodges Toby,

We wanted to share a figure that would help communicate the format of our CELSI work. See attached image. From this breakdown on the highlighted IDSov Workshop, we are thinking that it would be best to have the three parts built into one repository. Hopefully we are speaking the same language now as far as lessons and episodes. LMK if you have any questions.

[
<img width="1440" alt="CELSI_Carpentries" src="https://github.com/carpentries-incubator/proposals/assets/113132944/93ee6288-2151-462d-a99e-5131af00f22d">
](url)

**Comment by ErinBecker** [comment]
Hi @AndrewMartinez22. Very exciting to have the team ready to start populating content using The Carpentries lesson template! 

I have created the repository for you at https://github.com/carpentries-incubator/Indigenous-Data-Sovereignty

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriuclum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!
