### ISSUE TITLE
[Proposal]: RNA-Seq: data readiness for machine learning applications

### ISSUE THREAD

**Issue by parkyed** [carpentries-incubator/proposals#165]
### 1. Lesson Topic

Sourcing and pre-processing RNA-Seq (next generation sequencing gene expression) datasets for machine learning applications

### 2. Draft materials

Yes, but not available online at the moment.

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 6. Collaborators

I don't know at the moment, however I will find them out at a later date once the materials are further progressed.

### 7. Info/Questions

The materials are currently under development in R Markdown. Once the repo is available, I plan to transfer the materials to the new repo, using the appropriate template. I haven't yet put them in a github repo, hence not providing a link to the materials above. I hope you have the information that you require at this stage. Thanks!

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal @USERNAME.

I have created the repository for you at https://github.com/carpentries-incubator/rna-seq-data-for-ml.

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriuclum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!

**Comment by parkyed** [comment]
Dear Toby,

Thanks for setting up the repo.
I have developed the majority of the lesson and pushed to the repo.

I have build locally and previewed it and am pretty happy, so would like to share with colleague.

Is there a way to build the lesson to a test site public internet, or do my collaborators need to build it locally themselves? I just couldn’t find this in the Workbench documentation or by doing some basic google searches. I'm new to this, apologies if I'm missing something really obvious.

Thanks,
Ed

**Comment by tobyhodges** [comment]
Hi @parkyed I am not sure that I understand the question fully. But if you are asking how to provide the lesson you have written as a publicly-visible website you can share with your colleagues, I have good news for you! Your lesson site is already available at https://carpentries-incubator.github.io/rna-seq-data-for-ml/ - it is configured to be built from the `main` branch of the GitHub repository.

**Comment by tobyhodges** [comment]
I think this is a case of expert awareness gap on our part - we are so used to working with GitHub Pages websites that we have forgotten to mention it in the Workbench tutorial!

If you are interested in learning more about it, [the relevant episode of the Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/instructor/07-infrastructure.html) looks at setting up a lesson website with GitHub (no local setup, so the opposite of how you have been working!) and covers GitHub Pages setup early on.

**Comment by kerchner** [comment]
@parkyed This looks like an incredibly useful lesson. Once you have a first draft of all the sections, I'd love to run through it with some Bioinformatics colleagues here at GW.
