### ISSUE TITLE
[Proposal]: Collaborating and sharing using GitHub without command line

### ISSUE THREAD

**Issue by MikeTrizna** [carpentries-incubator/proposals#166]
### 1. Lesson Topic

GitHub without the command line

### 2. Draft materials

https://miketrizna.github.io/github-without-command-line/

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 7. Info/Questions

The draft lesson I linked to started as a fork of the Code Refinery "GitHub without Command Line" lesson (https://github.com/coderefinery/github-without-command-line) to teach internally at the Smithsonian. However, this fork has changed quite a bit and has matured enough to be taught a few times at the Smithsonian as part of a Data Carpentry workshop. I think we could strip out some of the Smithsonian-specific pieces to make it a general lesson that any Carpentries Instructor could teach.

**Comment by ErinBecker** [comment]
Thanks for this lesson proposal @MikeTrizna .

I have created the repository for you at https://github.com/carpentries-incubator/github-without-command-line.

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriuclum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!
