### ISSUE TITLE
[Proposal]: Introduction to the "targets" Package for Reproducible Data Analysis in R

### ISSUE THREAD

**Issue by joelnitta** [carpentries-incubator/proposals#167]
### 1. Lesson Topic

Introduction to the "targets" Package for Reproducible Data Analysis in R

### 2. Draft materials

https://joelnitta.github.io/targets-workshop/

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [ ] I need a new repository created

### 5. Transfer existing repository

- [X] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

**Comment by ErinBecker** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @joelnitta!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by joelnitta** [comment]
@ErinBecker I transferred the repo. Can you grant my access again?

**Comment by ErinBecker** [comment]
@joelnitta - Apologies for the flurry of GH notifications just now! 😂 You should have Maintain level access through the [targets-workshop-maintainers team](https://github.com/orgs/carpentries-incubator/teams/targets-workshop-maintainers). Please let me know if anything doesn't look right. GH permissions are still a bit of a mystery to me.

**Comment by joelnitta** [comment]
Looks good, thanks!
