### ISSUE TITLE
[Proposal]: FAIRification of RNAseq Data

### ISSUE THREAD

**Issue by robertmand** [carpentries-incubator/proposals#170]
### 1. Lesson Topic

FAIRification of RNAseq Data

### 2. Draft materials

Some of the preliminary work (pages 10-21):
https://docs.google.com/document/d/1j-z8uUNZhrpKRZ1NEny7p252q7jtc3r-whd8PfiO11M/edit?usp=sharing

### 3. Requirements for existing materials

- [ x] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [ x] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 7. Info/Questions

This lesson will join another: https://elixir-uk-dash.github.io/FAIR-Pointers/
Preliminary work has been performed, to take a real data example (RNAseq) and look at how it can be made FAIR.  
Looking to write this lesson and release by the end of September 2023.

[RNAseq](https://en.wikipedia.org/wiki/RNA-Seq) (RNA sequencing) is chosen here as an example of how to FAIRify data for a popular assay in the Life Sciences.  RNAseq data can be shared and curated in designated public repositories using established ontologies for describing protocols and biological material.

Some of the preliminary work (pages 10-21):
https://docs.google.com/document/d/1j-z8uUNZhrpKRZ1NEny7p252q7jtc3r-whd8PfiO11M/edit?usp=sharing

**Comment by ErinBecker** [comment]
Thanks for this lesson proposal @robertmand.

I have created the repository for you at https://github.com/carpentries-incubator/FAIRification-of-RNAseq-Data.

You should have received an invitation to join the maintainer team for this lesson. Please reply here to let me know when you have joined the team, and I will then be able to grant you Admin access to the repository and give you the ability to add and remove collaborators on the maintainer team.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).
