### ISSUE TITLE
[Proposal]: Image classification with convolutional neural networks

### ISSUE THREAD

**Issue by erinmgraham** [carpentries-incubator/proposals#171]
### 1. Lesson Topic

Image classification

### 2. Draft materials

https://github.com/erinmgraham/icwithcnn

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [ ] I need a new repository created

### 5. Transfer existing repository

- [X] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 6. Collaborators

@adeyinkaaa; @danny-meloncelli; @isaac-jennings,@jasonbell13

### 7. Info/Questions

Note The closest Carpentry repo we found for image classification with CNN's is the 'Introduction to deep learning' beta lesson. We took the '[Advanced layer types](https://carpentries-incubator.github.io/deep-learning-intro/4-advanced-layer-types.html)' episode from this lesson, deconstructed it into multiple episodes, and expanded on the topics presented.

**Comment by ErinBecker** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @erinmgraham!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by erinmgraham** [comment]
Hi Erin, thanks for the assistance. I think I have made the transfer if you have time to confirm.

**Comment by ErinBecker** [comment]
Thank you @erinmgraham. I've confirmed the transfer and set up permissions for yourself and the [ic-with-cnn-lesson-maintainers team](https://github.com/orgs/carpentries-incubator/teams/icwithcnn-lesson-maintainers). You have admin access to the repository and should be able to add and remove team members as needed. I recommend removing the [individual contributors who currently have write access](https://github.com/carpentries-incubator/intro-image-classification-cnn/settings/access) and encouraging them to accept the GitHub team invite. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!
