### ISSUE TITLE
[Proposal]: Introduction to Modern Fortran

### ISSUE THREAD

**Issue by astroDimitrios** [carpentries-incubator/proposals#172]
### 1. Lesson Topic

Introduction to Modern Fortran

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/astroDimitrios/intro-to-modern-fortran

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 8. Info/Questions

This lesson is no where near complete in the workbench format but this is what I used to test so I will be updating it and sharing with collaborators once up properly. This course transfers and modifies epcc/archer2's training course to use the Workbench format.

We discussed this at RSECon23 and have several collaborators already (once I work out what there handles are).

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @astroDimitrios!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and if you post the usernames of your collaborators here I will add them to the developer team to grant them "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by tobyhodges** [comment]
Thank you for transferring the repository @astroDimitrios. I have restored your Admin access and will close this issue now that the repository is set up. I will still receive notifications so please post back here if you have any questions or would like to add any collaborators to the organisation. I am always happy to help community members with curriculum development. Good luck with the lesson!

**Comment by astroDimitrios** [comment]
@tobyhodges Many thanks - I have transferred the repository. The link to become a member of the slack channel/workspace didn't work, is there another link I can try?

**Comment by tobyhodges** [comment]
Ah yes, the URL recently changed I forgot to use the new one here. You should be able to join the Slack workspace via https://slack-invite.carpentries.org/

**Comment by astroDimitrios** [comment]
Can you add @TeranIvy , @joeHickson , and @EdHone please?
I will get back to you when the other maintainers have sent me their GitHub. Thanks!

**Comment by tobyhodges** [comment]
Done @astroDimitrios, and I've made you a maintainer of the maintainer team so I think you will be able to add more members yourself if and when you need to.

**Comment by astroDimitrios** [comment]
Hi @tobyhodges  thanks! I am trying to add @juanfrh but I think he needs to be a member of the organisation first? Is that something I am able to do? TIA

**Comment by tobyhodges** [comment]
You're right, I need to invite people to be members of the organisation before you can add them to a team. That's a frustrating additional step, but I am happy to send out invitations as needed so please ping me again if and when you want to add more collaborators.

**Comment by astroDimitrios** [comment]
@tobyhodges can we also add JMorado please?

**Comment by astroDimitrios** [comment]
@tobyhodges and samharrison7 when you have a moment please :)

**Comment by astroDimitrios** [comment]
@tobyhodges also Shahid718 please!
