### ISSUE TITLE
[Proposal]: GitHub Skill-up for Instructors

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/proposals#173]
### 1. Lesson Topic

GitHub Skill-up for Carpentries Instructors

### 2. Lesson Language

English

### 3. Draft materials

http://sarahlrstevens.info/github-skill-up-instructors/

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@tobyhodges

**Comment by sstevens2** [comment]
Went ahead and transferred.  I believe I need access again and maybe we need to turn on gh-pages (at least need to link it in the about again).  Also need to update the config I think to have the new web address
Not sure if @tobyhodges is officially back so tagging @ErinBecker just in case.
Need this done soon as I'm teaching it Sept 15th and might find additional changes between now and then.

**Comment by sstevens2** [comment]
It is already rendering which is nice - https://carpentries-incubator.github.io/github-skill-up-instructors/

**Comment by tobyhodges** [comment]
Thanks for going ahead with the transfer, @sstevens2. I have restored your Admin access, and added you to a developer team for the skill-up. If and when you gain collaborators to help you with this skill-up, you can add them to that team to grant them Maintain access. (They may need to join the organisation first.)

Now that the transfer is complete and you access is restored, I will close this issue. Please post back here if you run into any trouble or have any more questions. Good luck with the skill-up session on Friday!

**Comment by sstevens2** [comment]
Thanks Toby!
