### ISSUE TITLE
[Proposal]: Geospatial Data Carpentry with R for Urbanists

### ISSUE THREAD

**Issue by cforgaci** [carpentries-incubator/proposals#174]
### 1. Lesson Topic

Geospatial Data Carpentry with R for Urbanists

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/Rbanism/geospatial-data-carpentry-tud.git

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [X] I need a new repository created

### 6. Transfer existing repository

- [ ] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@alwil
@ClementineCttn
@dcannatella
@KyriJanssen
@manuGil
@fcjerome
@ana-5r

### 8. Info/Questions

Dear @tobyhodges,

We've been developing and running this as a Mix & Match workshop based on the **Data Carpentry with R for Social Sciences and Humanities** and the **Data Carpentry for Geospatial Data with R** at TU Delft in the Netherlands. To meet the needs of our target community—researchers of the urban environment—, we've adapted the content extensively as follows:
- added a half-day intro to R at the beginning of the workshop based on our experiences in the DC with R for SSH;
- removed parts that are not commonly used in research, mostly parts of the lesson using raster data;
- allocated vector and raster data in the second and third dayparts of the workshop, respectively, and trimmed the content to fit that time;
- replaced the vector and raster data with data relevant for urbanists;
- added the last half day with new lessons combining vector and raster data in domain-specific questions;
- adapted the exercises to match the new data and lessons.

After two successful pilot runs of this workshop, we will continue to run it at least once a year and thus would like to put it forward in the Carpentries Incubator.

Regarding point 6 in this template, our lessons do not use the Carpentries Workbench template yet, but we can transfer the content to it so that it can be transferred to the Carpentries Incubator.

We look forward to your feedback on how we can take this further.

Claudiu Forgaci
[Rbanism](https://rbanism.github.io/Rbanism/)

**Comment by tobyhodges** [comment]
@cforgaci it looks like I mistakenly used the wrong template repository yesterday, which means that some of the files are outdated. If you haven't already started working with it, I would like to delete the repsitory and create a new one from the correct version of the template. Is that okay? I'm sorry for the confusion.

**Comment by cforgaci** [comment]
@tobyhodges that is okay. Feel free to create a new repository. Thanks for taking care of this.

**Comment by tobyhodges** [comment]
Thanks both. I have deleted and re-created the repository at the same URL using the most up-to-date template. You should be good to go now! I am going to close this issue but please post back here if you have any questions or run into any problems.

**Comment by cforgaci** [comment]
@tobyhodges, our workshop material is ready for beta testing. Note that this workshop is run by our team in person once per year at TU Delft and that we have already taught it four times. The current material is the result of revisions we made around those runs.

Let us know if there's anything we can or need to do to start the testing process. Many thanks in advance!

**Comment by tobyhodges** [comment]
@cforgaci exciting! Thanks for letting me know. I can help you look for Instructors who could beta test the lesson. I will follow up with you by email.
