### ISSUE TITLE
[Proposal]: Advanced Git Workshop 

### ISSUE THREAD

**Issue by ivastar** [carpentries-incubator/proposals#179]
### 1. Lesson Topic

Advanced Git 

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/ivastar/advanced-git

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

https://github.com/ivastar/advanced-git/blob/gh-pages/AUTHORS

### 8. Info/Questions

Hello!

I and the other authors have taught a number of workshops based on these materials. They can fit into ~ a half day. We have advertised this not as a sequel to the intro git but rather recommend that participants have at least 6 months of active git use after the intro workshop before they take the workshop.

The materials are in the old Carpentries format but only approximately so. Most lessons are screen grabs of images from the power point presentation that was used to teach this workshop. It needs more work to actually have fleshed-out lessons, which is why I am submitting it to the incubator. If there an interest in this level materials, I would love to have more people contribute to this set of lessons. 

All the best,
-Iva Momcheva

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @ivastar!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights and any collaborators you want to be added will be given 'Maintain' access.

To suggest a few ways you might attract the attention of others in the community who would like to contribute to the development and maintenance of the lesson, you could post a message to the `#swc-git` and `#lesson-dev` channel on The Carpentries Slack workspace, or even write a short blog post (perhaps using [the _Incubator Lesson Spotlight_ format](https://docs.carpentries.org/topic_folders/lesson_development/spotlight.html)?) to tell the community about the project and how they can get involved.

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by ivastar** [comment]
Hi @tobyhodges! I just initiated the transfer. I look forward to developing the materials with the Carpentries community.

**Comment by tobyhodges** [comment]
Thank you @ivastar. I restored your Admin access to the repository so you should be all set. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!
