### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ErinBecker** [carpentries-incubator/proposals#18]
These materials were previously listed on the DEPRECATED [sharing-lessons Etherpad](https://pad.carpentries.org/sharing-lessons). 

https://dme26.github.io/docker-introduction/

**Comment by ErinBecker** [comment]
@dme26 - We've just created The Carpentries Incubator GH organization to provide a single point of entry for community members to share lesson materials and discuss ideas for new lessons. Your lesson materials were previously listed on the sharing-lessons Etherpad, which has now been deprecated. All of the resources listed on that pad have been migrated here. We're still working on organizing this repo, so please do let me know if you have ideas for how best to organize this information to make it accessible to the community.

**Comment by dme26** [comment]
Thanks for migrating these materials, @ErinBecker ! I'll try to answer the questions that were in the issue template—but let me know if you'd just like me to open a separate issue.

> 1. What is the topic of your lesson or lesson proposal?

An introduction to Docker, as by the URL, but the title is currently "Reproducible computational environments using containers".

> 2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes, as at the [above link](https://dme26.github.io/docker-introduction/), but I'd be keen to migrate  it to The Carpentries Incubator GH organization.

> 3. Do your materials conform to our [Code of Conduct][coc]?

Yes, it is my intention that they do.

> 4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 

"Yes" to GitHub hosting.

When deploying The Carpentries template I tried to remove any explicit and implicit links to The Carpentries to avoid any incorrect implication of endorsement of my materials by The Carpentries, however this required some explicit patching of the template (I intend to try to contribute tweaks to the template to try to make this process easier).

> 5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

It may be most appropriate for the Curriculum Team to create a new stub repository with the approved template (see Q4 discussion): I can then rapidly merge in my actual lesson materials (which should already conform to the template, technically). 

> 6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

Yes, I would like to transfer my repository to The Carpentries Incubator (after the template cleaning).

> 7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

@dme26
@sstevens2

> 8. Any other information you would like us to have or questions you have for us?

Not yet. Thanks for all your work on this!

**Comment by sstevens2** [comment]
Let me know if there is anything I can do to help with this process!

**Comment by ErinBecker** [comment]
Sorry for the delay on responding to this @dme26 and @sstevens2! I'll get that repo set up for you first thing in the morning!

**Comment by ErinBecker** [comment]
Sorry again for the delay @dme26 and @sstevens2. I was experimenting with a new system for filtering my emails and GH notifications and it failed me - going to go back to my default of just marking things unread! Anyway, here's the repo: https://github.com/carpentries-incubator/docker-introduction. The two of you should have email invitations to join the rep with Write access. If something looks wonky or doesn't work, please let me know! I'll close this issue when I see you both accept the GH invite. 🙂

**Comment by ErinBecker** [comment]
Ok to close this issue?

**Comment by dme26** [comment]
Yes, thanks @ErinBecker !
