### ISSUE TITLE
[Proposal]: Pangenomics and Topological Data Analysis

### ISSUE THREAD

**Issue by Czirion** [carpentries-incubator/proposals#181]
### 1. Lesson Topic

Pangenomics analysis in prokaryotes and Topological Data Analysis

### 2. Lesson Language

English

### 3. Draft materials

https://czirion.github.io/pangenomics-workshop/

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@nselem @paumayell @shadayguerrero @HaydeePeruyero @solnavss

**Comment by Czirion** [comment]
Hi @tobyhodges, thanks for your response. We believe that the best would be to have only the existing team and add the new members to it.

**Comment by Czirion** [comment]
The team developing the Pangenomics Workshop that is missing from https://github.com/orgs/carpentries-incubator/teams/metagenomics-pangenomics-maintainers are @paumayell @shadayguerrero @HaydeePeruyero @solnavss @fabel134

**Comment by tobyhodges** [comment]
Thanks @Czirion I have invited the colleagues you listed to join that team.

Please go ahead and transfer the repository into the Incubator, and let me know when you have done it so that I can take care of a few administrative things.

**Comment by Czirion** [comment]
Hi @tobyhodges,
I already transferred the repositories that were under my name. To transfer the ones owned by @paumayell , could you please invite her again to the team? Sorry, I did not think about asking her to check the invitation on time and now it has expired. 
Thank you

**Comment by tobyhodges** [comment]
Thanks @Czirion I have re-sent the invitation. I will close this issue now that the repository has been transferred, but will still receive notifications for the thread so please continue to post here if you have further questions/need more help.

**Comment by Czirion** [comment]
Hello @tobyhodges 
Is the repository [pangenomics-python]( https://github.com/carpentries-incubator/pangenomics-python) associated with our development Team? I can commit in the repository but some of the people in the team can't. Also, I don't see the Settings tab in that repo, which I can see in the others. 
Thank you

**Comment by tobyhodges** [comment]
Sorry @Czirion I must have missed that one before. I have updated the permissions now.

**Comment by Czirion** [comment]
Thank you @tobyhodges !
