### ISSUE TITLE
Genome Mining Workshop

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/proposals#183]
### 1. Lesson Topic

Introduction to Genome Mining

### 2. Lesson Language

English

### 3. Draft materials

https://czirion.github.io/genome-mining-workshop/

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@Czirion @DianaOaxaca @shadayguerrero @fabel134

**Comment by tobyhodges** [comment]
Thank you for the lesson proposal, @nselem. Is this another part of the Pangenomics curriculum? If so, would you like to use the same maintainer team for this lesson as the others? Or would it be better to create a new team of maintainers for this one?

**Comment by nselem** [comment]
Hello Toby, 
I think it is better to have a new maintainer team. As a workshop, it starts with Pangenomics first three lessons, but it ends with a Genome Mining instead of Topological Data Analysis. The Genome Mining mantainers would be a different team.

**Comment by tobyhodges** [comment]
Great, I have created the https://github.com/orgs/carpentries-incubator/teams/genome-mining-workshop-maintainers team, and added/invited you all to join it. @Czirion can transfer the repository, adn I will restore your admin/maintainer access to it ASAP afterwards.

**Comment by Czirion** [comment]
Thank you @tobyhodges ! I just transferred the landing repo. Can you add @AxelRamosGarcia to the team, please ?

**Comment by tobyhodges** [comment]
Thank you for making the transfer, @Czirion. I have granted the team Maintain access to the repository, and Admin access to you and @nselem. I also invited @AxelRamosGarcia to the team as you requested. 

I will close this issue now that the repository has been transferred into the Incubator, but I will still receive notifications so feel free to respond here if you need anything else.

**Comment by nselem** [comment]
Hello Toby
Please Toby could you add paumayell, Galn3x, andrespan and DianaOaxaca to the mantainers team of all the lessons of the workshop?

**Comment by tobyhodges** [comment]
@DianaOaxaca was already a member, and I have now invited the others 👍
