### ISSUE TITLE
[Proposal]: FAIR for busy biologists

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/proposals#184]
### 1. Lesson Topic

Introduction to FAIR principles and good data managment

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/BioRDM/fair-for-busy-biologists

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [X] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@liviascorza 

### 8. Info/Questions

In addition to the existing FAIR courses offered by Carpentries (FAIR 4 Leaders and FAIR in (bio) practice), we developed a shorter version focusing on core skills. This was motivated by the high valuation of the "FAIR in (bio) practice" but the limited participation due to its 16-hour length.

The new course can be delivered in two 3-hour sessions, making it more accessible. We successfully piloted the course last week, verifying the timing and receiving positive feedback. Importantly, the course was filled, and there were even requests to join after registration closed.

The original, longer FAIR course remains valuable. We've observed elements being reused for teaching this subject, and we still direct students to the full version for in-depth learning.

**Comment by tobyhodges** [comment]
So sorry I missed this, @tzielins. Thank you for submitting the lesson to The Carpentries Incubator.

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://slack-invite.carpentries.org/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by tzielins** [comment]
@tobyhodges  I created the repo with the lesson content:
https://github.com/carpentries-incubator/fair-for-busy-biologists

I believe everything works as it should.
