### ISSUE TITLE
[Proposal]: Trustworthy AI: Explainability, Bias, and Fairness

### ISSUE THREAD

**Issue by qualiaMachine** [carpentries-incubator/proposals#185]
### 1. Lesson Topic

Trustworthy AI: Explainability, Bias, and Fairness

### 2. Lesson Language

English

### 3. Draft materials

https://annapmeyer.github.io/fair-explainable-ml/ and https://docs.google.com/document/d/1W2IKH7HGMmRmHTzqCfOxrmi-sr8BDb71Z_EBMH1oUpk/edit?usp=sharing

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@qualiaMachine, @annapmeyer, @uppaal, yiqiaozhong10@gmail.com

### 8. Info/Questions

We have reached out and discussed this workshop with Tom Pollard, who developed a somewhat similar workshop: https://carpentries-incubator.github.io/machine-learning-responsible-python/ 

Tom's workshop is much more conceptual (and much shorter), and he agreed it made sense to branch off and do a new workshop that is more focused on hands-on implementations of the concepts Tom covers in his workshop. We believe it's best to have both options because not everyone needs the hands-on implementations — some just need to be quickly briefed on these important issues.

Also, we are in the early stages of transferring our google doc material to the github repo. The repo will look much more fleshed out in the coming weeks.

**Comment by qualiaMachine** [comment]
Thanks, Toby! We have completed the transfer. If possible, can you make both me and @annapmeyer admins on this repo?

**Comment by tobyhodges** [comment]
Done! Thank you @qualiaMachine.

I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!
