### ISSUE TITLE
[Proposal]: Task Management as Self-Care

### ISSUE THREAD

**Issue by jezcope** [carpentries-incubator/proposals#188]
### 1. Lesson Topic

Task Management as Self-Care

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/olexandr-konovalov/task-management

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@olexandr-konovalov (current repo owner)
@bisaloo
@amangoel185
@mdsimpson42
@selina-aragon
@nickynicolson
@matscorse

### 8. Info/Questions

Developed as part of [CW24 hackday](https://www.software.ac.uk/cw24-hack-day). Slide deck overview temporarily at https://bl-presentations.erambler.co.uk/2024-05-02-cw24-hackday/

**Comment by tobyhodges** [comment]
Hi @jezcope, thank you for submitting this lesson to The Carpentries Incubator. It looks like you all had a productive CW24!

You and your collaborators should have received an invitation to join a Team of maintainers (`task-management-maintainers`) for the lesson, as part of the `carpentries-incubator` organization on GitHub. @olexandr-konovalov should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you and Olexandr will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://slack-invite.carpentries.org/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by olexandr-konovalov** [comment]
@tobyhodges thank you! It's now at https://github.com/carpentries-incubator/task-management - could you please update admins and collaborators.

**Comment by tobyhodges** [comment]
Thank you @USERNAME. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!

**Comment by olexandr-konovalov** [comment]
Thanks @tobyhodges! I've updated the repository details to point it to https://carpentries-incubator.github.io/task-management/ as the lesson website.

**Comment by jezcope** [comment]
Amazing, thanks so much both! Now to figure out what comes next…
