### ISSUE TITLE
[Proposal]: Particle Physics in Python

### ISSUE THREAD

**Issue by YeungOnion** [carpentries-incubator/proposals#189]
### 1. Lesson Topic

Introduction to Particle Physics in Python

### 2. Lesson Language

English

### 3. Draft materials

No

### 4. Requirements for existing materials

- [ ] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [X] I need a new repository created

### 6. Transfer existing repository

- [ ] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@YeungOnion

### 8. Info/Questions

In my experience from within, physics in many areas has felt like an insular and slightly elitist community. I'm hoping that you have avenues for obtaining feedback from other particle physicists that may have some capacity to bring in those who would support and develop a welcoming and inclusive community.

I know of some people from the particle physics RSE domain that give the vibe of being welcoming and open with their work, but I don't know them personally. Perhaps someone knows either Brian Bockelman @ UW-Madison, USA; Ian Cosden, Henry Schreiner @ Princeton University, USA. They may have the connections/capability to migrate students into relying on, appreciating, and contributing to The Carpentries lessons.

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal @YeungOnion.

I have created the repository for you at https://github.com/carpentries-incubator/python-particle-physics/.

You should have received an invitation to join the maintainer team for this lesson. Please reply here to let me know when you have joined the team, and I will then be able to grant you Admin access to the repository and give you the ability to add and remove collaborators on the maintainer team.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

> I'm hoping that you have avenues for obtaining feedback from other particle physicists that may have some capacity to bring in those who would support and develop a welcoming and inclusive community.

I cannot help with this directly, but I expect you could attract the attention of these folks by making some noise about the lesson on the right communications channels. [The Carpentries Slack workspace](https://carpentries.org/connect/) is probably a good place to start. You might get a direct response there and/or people might pass the link on to colleagues they know could be interested. 

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3).

**Comment by YeungOnion** [comment]
Hi @tobyhodges,

I was on vacation last week and the invite expired. I'll keep an eye out for the next one if you can send that!

**Comment by tobyhodges** [comment]
@YeungOnion It looks like you have full access to the repository now. I will close this issue now but I will still receive notifications so please post back here if you have any questions!
