### ISSUE TITLE
[Proposal]: Add "HPC Workflow Management with Maestro"

### ISSUE THREAD

**Issue by xorJane** [carpentries-incubator/proposals#192]
### 1. Lesson Topic

HPC workflows, Maestro

### 2. Lesson Language

English

### 3. Draft materials

https://xorjane.github.io/maestro-workflow-lesson/

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 8. Info/Questions

This lesson was taught as part of an [HPC Carpentry workshop](https://www.hpc-carpentry.org/blog/2024/08/llnl-workshop-blog-post.html) held in June 2024. It is based on [this workflow lesson in snakemake](https://carpentries-incubator.github.io/hpc-workflows/).

Thank you for reviewing!

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @xorJane! I enjoyed reading about your lesson in the workshop report you linked to.

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by xorJane** [comment]
Thanks @tobyhodges! I just initiated the transfer. :)

**Comment by tobyhodges** [comment]
Thank you @xorJane. A good next step might be to update the `source` parameter in your lesson's `config.yml` to reflect the new location of the lesson repository. 

I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!
