### ISSUE TITLE
[Proposal]: Medical Image Processing in Python

### ISSUE THREAD

**Issue by drcandacemakedamoore** [carpentries-incubator/proposals#196]
### 1. Lesson Topic

Medical Image Processing in Python

### 2. Lesson Language

English

### 3. Draft materials

https://esciencecenter-digital-skills.github.io/medical-image-processing/

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [x] I need a new repository created

### 6. Transfer existing repository

- [x] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 8. Info/Questions

Is it better to transfer to the Carpentries Incubator, or can we become a Carpentries lesson without this?

**Comment by tobyhodges** [comment]
> Is it better to transfer to the Carpentries Incubator, or can we become a Carpentries lesson without this?

Although it is not required I would say it is better to transfer the lesson into the Incubator, @drcandacemakedamoore: this significantly increases the visibility of the lesson to the wider Carpentries community, and makes it easier for us to support you as you continue to develop the lesson.

If you intend for the lesson to join one of the existing lesson programs (maybe Data Carpentry, given the lesson topic?), I recommend that you contact the relevant [Curriculum Advisory Committee](https://carpentries.org/curriculum-advisors/) -- given some time to discuss it, they will be able to provide advice and guidance to help you prepare the lesson for adoption.

**Comment by drcandacemakedamoore** [comment]
We have decided to move to Carpentries Incubator pending approval. I have written the curriculum advisory committee about this. Is there anything else I need to check off here to move lesson @tobyhodges ?

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @drcandacemakedamoore, and for your patience.

You and should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://slack-invite.carpentries.org/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by tobyhodges** [comment]
Thank you for making the transfer @drcandacemakedamoore. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!

**Comment by drcandacemakedamoore** [comment]
We can remove these as a precaution if you guys want. They do draw heavily
from the linked lessons, but were evolving away from them. Please let us
know as soon as possible.

**Comment by tobyhodges** [comment]
Thanks for raising this, @jhlegarreta. Indeed, the [_Working with MRI_ episode](https://carpentries-incubator.github.io/medical-image-processing/mri.html) includes [a list of lessons from which content has been taken](https://carpentries-incubator.github.io/medical-image-processing/mri.html#introduction). If you would like more extensive/detailed attribution -- and especially if there is anything missing from that list -- please let the authors know how they can provide that via an issue on the repository. I have [opened a pull request to clarify that these are Incubator lessons](https://github.com/carpentries-incubator/medical-image-processing/pull/61), rather than The Carpentries' own.

I spoke with @drcandacemakedamoore about the lesson last week, and we briefly discussed the potential overlap with the existing *MRI lessons. I believe the rationale for creating a separate lesson instead of contributing to that established curriculum is that this lesson is intended to provide an overview, rather than try to cover everything in depth.

**Comment by drcandacemakedamoore** [comment]
So I have added the update from @tobyhodges . To get a sense of where the material went in terms of current divergance you will need to see the draft PR here https://github.com/carpentries-incubator/medical-image-processing/pull/57 @jhlegarreta  and actually it kept even further evolving from the materials but unfortunately, the new MRI materials await approval from the other main maintainer (gcrocioni) who can not work on it until January. Therefore, we can temporarily just pull all MRI stuff offline if needed, until the new stuff comes in next year. Let us know if that is needed.

**Comment by drcandacemakedamoore** [comment]
So, as a precaution, I've just taken the MRI stuff offline now. It can all be slowly discussed with everyone evolved before any of it returns online. I hope this is satisfactory @jhlegarreta and @tobyhodges . I would however like to note that the materials were rewritten by more than one person in a group effort.

**Comment by tobyhodges** [comment]
To be clear, the CC-BY license only requires that attribution is given to the source of the re-used material. Although I am not a lawyer, in my view the introduction to the episode -- with links to the individual lessons from which content was taken -- fulfilled this requirement. Above, I invited @jhlegarreta to specify if he felt any more detailed attribution was required, as it is more important that you meet his definition of what is sufficient than my own. 

But, @drcandacemakedamoore you are not obliged to remove any material from your lesson, or make any other changes, as long as you respect the CC-BY license of the original MRI lessons.

I do share @jhlegarreta's desire to avoid duplication of effort: this was one of the main reasons for creating the Incubator in the first place. That is why it was important for me to make sure that  @drcandacemakedamoore was aware of the other *MRI etc lessons before I processed the submission. 

But if lesson developers are aware of existing projects on similar topics and still choose to create their own, I should not stand in their way. If nothing else, the alternative might encourage ["cookie licking"](https://en.m.wiktionary.org/wiki/cookie_licking).

**Comment by drcandacemakedamoore** [comment]
Well whatever the case for now this particular lesson is currently removed so there can be more discussion with the creators of each of the other lessons; some of which I may have incorrectly assumed were abandoned because they seemed broken in some places. I think it is possible some of the maintainers did not really mean to be CC-BY-4.0 and I would like to give a chance to change this, and suggest ways to complement each other's lessons if this is the prefered strategy. @jhlegarreta how can I get in touch with you to schedule a meeting? And do you know if there is any forum where I can quickly contact all the maintainers?

**Comment by jhlegarreta** [comment]
@drcandacemakedamoore We used to use a channel (#neuroimaging) in the Carpentries Slack and meet every two weeks when the contents were being actively added, shaped, improved, etc. There has not been a lot of activity there lately for various reasons, but maybe you can try to tag people there. In order to talk to schedule a meeting with me, you will easily find my email address if you look for my name on the internet (e.g. scientific articles, etc.)

**Comment by drcandacemakedamoore** [comment]
@jhlegarreta I'm trying to reach you on LinkedIn as I had trouble finding your email. I'm not on the Carpentries Slack, but if the channel is dead, maybe it isn't the best way anyways. Please respond to my Linkedin or send an alternative contact method. Thanks!

**Comment by jhlegarreta** [comment]
@drcandacemakedamoore Replied.
