### ISSUE TITLE
[Proposal]: AI-assisted Coding with Codeium

### ISSUE THREAD

**Issue by gcroci2** [carpentries-incubator/proposals#203]
### 1. Lesson Topic

Learn how to configure and use AI coding assistants to generate, refactor, and improve code, automate repetitive tasks, and improve documentation.

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/olgaminaeva/gen-ai-coding

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@olgaminaeva

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @gcroci2! I am really excited to see it here.

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and Olga will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://slack-invite.carpentries.org/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by gcroci2** [comment]
Hi @tobyhodges! Thanks for the invitation, I've just accepted it. I think that also [@olgaminaeva](https://github.com/olgaminaeva) needs to be invited as a maintainer, and she's the one to have permissions to move the lesson repository (since it lives now on her profile). Once she will be a maintainer as well she can transfer the repository into `carpentries-incubator`.

**Comment by olgaminaeva** [comment]
Hi @tobyhodges, thank you for the invitation to the Carpentries Incubator. I just transferred the repository into `carpentries-incubator`, and I hope it worked out.

**Comment by tobyhodges** [comment]
Hi both, thank you for making the transfer. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!
