### ISSUE TITLE
Data Science for Doctors

### ISSUE THREAD

**Issue by docsteveharris** [carpentries-incubator/proposals#22]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Data carpentry orientated toward practicing clinicians - most specifically those working in the NHS

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes. We have materials built using the old lesson templates here

https://github.com/datascibc/Data-Science-for-Docs

And an updated version using newer data and improved material but not based on the original templates that is in a private repo whilst we clean out some data.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

I believe so.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 

Yes. But probably an old version

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

aasiyahrashan
doced

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
Hi @docsteveharris - thanks for submitting this proposal! Would you prefer for us to create a new repo for you in the Incubator org or to transfer over your existing repo?

**Comment by docsteveharris** [comment]
Does transfer mean that the original repo becomes owned by the incubator? If so then perhaps create a clean one, and we will populate?

——
Primary email: doc@steveharris.me
Secure email: s.harris8@nhs.net
mobile: 07977 583315

**Comment by ErinBecker** [comment]
Great question. You will retain ownership of your lessons, according to whatever license you have attached to the materials (the license must be either CC-BY or CC-0 in order to be hosted in the Incubator). 

Since it looks like the lesson uses a pretty old version of our lesson template, starting a fresh repo with our current template and transfering over the lesson contents would probably be the easiest way to get things up to date. I'll go ahead and create this, and give write access to: @datascibc, @aasiyahrashan, @docsteveharris, and @doced.

**Comment by ErinBecker** [comment]
@docsteveharris - Your new repo is https://github.com/carpentries-incubator/Data-Science-for-Docs and renders at https://carpentries-incubator.github.io/Data-Science-for-Docs/. I've sent invites to @aasiyahrashan, @docsteveharris, and @DocEd to join a team titled "Data-Science-for-Docs-maintainers". Once they've joined that team, they should have write access to the repo. I wasn't able to send an invite to @datascibc, but I see that that group is owned by @tompollard. Should I add @tompollard to the team? 

One last note - the template comes pre-populated with a [CC-BY license](https://carpentries-incubator.github.io/Data-Science-for-Docs/LICENSE.html), which is the license used by all The Carpentries lessons. Please read through that license and make sure you're ok using it on these materials before transferring content over. Happy to answer any questions that come up!

**Comment by docsteveharris** [comment]
Hi Erin

Could you also add

@dannyjnwong
@finncatling
@ngageorange

And don’t add @tompollard: he’s moved on to another lab and was not involved with this work.

Steve

——

**Comment by ErinBecker** [comment]
Done! Thanks for the list. I'll close this issue now, but please feel free to re-open if you have questions about migrating the content.
