### ISSUE TITLE
Pymarc in LC  

### ISSUE THREAD

**Issue by jayGattusoNLNZ** [carpentries-incubator/proposals#26]
1. What is the topic of your lesson or lesson proposal?

Beginners lesson for using the pymarc library )with python) to read, create,  and update MARC records 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No - very early stages. 

Checking for existing work/materials at this stage

**Comment by ErinBecker** [comment]
Thanks for starting an issue @jayGattusoNLNZ. It looks like at this point you're just looking for others who are interested or who have already developed materials. I'll leave this issue open. Please ping me when you'd like a repo created to start organizing ideas!

**Comment by tobyhodges** [comment]
Since #49 was accepted and https://github.com/carpentries-incubator/pymarc_basics created, can this be closed? Or is the lesson proposed here separate from that pyMARC intro? @jayGattusoNLNZ

**Comment by jayGattusoNLNZ** [comment]
lesson is now incorporated into the incubator
