### ISSUE TITLE
Introduction to Open Data Science with R

### ISSUE THREAD

**Issue by mgalland** [carpentries-incubator/proposals#29]
1. What is the topic of your lesson or lesson proposal?
To show how R/RStudio can be combined with git/Github to promote Open Science through literate programming and collaboration.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes. It can be found here: https://github.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training

3. Do your materials conform to our [Code of Conduct][coc]?
Yes they do. 

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 
Yes they do. 
https://github.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training
https://scienceparkstudygroup.github.io/r-lesson-based-on-ohi-data-training/

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 
Yes with pleasure. 

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 
Don't really know I must say. 

8. Any other information you would like us to have or questions you have for us?
This materials borrow heavily from the Ocean Health Index data training.  I would like them to be aware of what I've done so far and see if they would like to contribute.  https://github.com/OHI-Science/data-science-training

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
Thanks for sharing your materials @mgalland! I've added you as a member to the carpentries-incubator GH organization, so you should now have the ability to transfer your repository. Once you've done that, I'll make sure that the permissions are correct and get the lesson tagged so it can show up on our [community lessons page](https://carpentries.org/community-lessons/). 

One question - the original materials that you point to are licensed with the [MIT license](https://github.com/OHI-Science/data-science-training/blob/master/LICENSE). This seems very similar to a CC-BY license, but may not be recognized internationally. Would you be willing to contact those content authors and ask them if licensing a derivative work with a [CC-BY license](https://creativecommons.org/licenses/by/4.0/) would be acceptable? CC licenses are specifically designed to maximize their applicability across borders.

**Comment by mgalland** [comment]
Hello @ErinBecker 
Thank you for your follow-up. I've imported the lesson in the Carpentries Incubator and renamed it (open-science-with-r).  
Yes, I'll send the authors a small email to see if the license can be changed. 
Thanks again for your help,
Best
Marc

**Comment by mgalland** [comment]
Hello Erin, 
This is the answer I've just received from Julie Lowndes, one of the authors from the lesson. 
You can go ahead and change the license to CC-BY. 
Cheers
Marc

=====
Hello Marc,

Yes, I have just changed the LICENSE in the github repo and added the CC-BY label to the front of the rendered book (ohi-science.org/data-science-training).

Cheers,
Julie
====

**Comment by ErinBecker** [comment]
Excellent, thanks @mgalland!
