### ISSUE TITLE
Introduction to Conda for (Data) Scientists

### ISSUE THREAD

**Issue by davidrpugh** [carpentries-incubator/proposals#32]
1. What is the topic of your lesson or lesson proposal?

This lesson is an introduction to Conda for (data) scientists. Conda is an open source package and environment management system that runs on Windows, macOS and Linux. Conda installs, runs, and updates packages and their dependencies. Conda easily creates, saves, loads, and switches between environments on your local computer. While Conda was created for Python programs it can package and distribute software for any languages such as R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, FORTRAN. This lesson motivates the use of Conda as a development tool for building and sharing project specific software environments that facilitate reproducible (data) science workflows.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://kaust-vislab.github.io/introduction-to-conda-for-data-scientists/

3. Do your materials conform to our [Code of Conduct][coc]?

Yes!

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 

Yes!

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

NA

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

@davidrpugh

**Comment by ErinBecker** [comment]
Hi @davidrpugh - thank you for your material submission! You are a member of the carpentries-incubator GH organisation, which should allow you to transfer your repository to this org. Once the repo is transfered, you should retain admin access and will be able to add any collaborators that you'd like to have write access to your lesson. @fmichonneau will follow-up with any template updates that need to be imported into your repository in order to get your lesson listed on our community lessons page.

**Comment by fmichonneau** [comment]
@davidrpugh please let me know when you've transferred your lesson and I'd be happy to update the lesson template. Thanks!

**Comment by davidrpugh** [comment]
@fmichonneau I am teaching this material later this afternoon and don't want to move the repo until after the course as I may need to change links. Either later this afternoon or tomorrow I will transfer the repo.

**Comment by fmichonneau** [comment]
perfect!

**Comment by davidrpugh** [comment]
I have initiated the transfer of the repository.

**Comment by davidrpugh** [comment]
@fmichonneau I will be making some updates to the training materials based on my most recent teaching of the material. Can I start making these changes or would it be better for my to wait for you to apply updates to the template?

**Comment by davidrpugh** [comment]
@fmichonneau I noticed that I don't seem to have required permissions to update the website on the `carpentries-incubator/introduction-to-conda-for-data-scientists` repository. Is this intended? Website needs to be 

https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/

**Comment by fmichonneau** [comment]
sorry about that! You now have write access to the repository. Is there anyone else working on the lesson who should have access?

**Comment by davidrpugh** [comment]
﻿Thanks! At the moment no one else needs write access.

Are you still planning on adding changes to the template?

**Comment by fmichonneau** [comment]
With https://github.com/carpentries-incubator/introduction-to-conda-for-data-scientists/pull/19 now open, I think we can close the issue here. Thanks for your submission @davidrpugh!
