### ISSUE TITLE
GPU speedups in Python

### ISSUE THREAD

**Issue by geoffwoollard** [carpentries-incubator/proposals#33]
1. What is the topic of your lesson or lesson proposal?
GPU speedups in Python (cupy, numba, pycuda)

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://github.com/geoffwoollard/gpu-speedups-mbptechtalk2020

3. Do your materials conform to our [Code of Conduct][coc]?

Yes (I think so). [This](https://github.com/geoffwoollard/gpu-speedups-mbptechtalk2020/blob/master/LICENSE) is the license from the repo I forked from. One of the notebooks also comes from [this](https://github.com/jtc42/pycuda-convolution) repo, with no explicit license, but that is meant to be shared open teaching material.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 

GitHub. No, they do not use the lesson template. Note: My repo contains notebooks that the attendees run on google colab, and therefore have access to a free GPU. Also there are some modules already installed on google colab. So people are not intended to run the notebooks on their local laptop, etc.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

Just me, @geoffwoollard

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
@fmichonneau - would you mind creating an empty lesson for @geoffwoollard?

**Comment by ErinBecker** [comment]
Hey @fmichonneau, think you might have missed this one in your inbox. Could you please initialize a lesson repo for @geoffwoollard? Thanks.

**Comment by fmichonneau** [comment]
@geoffwoollard I set up the repository for your lesson here: https://github.com/carpentries-incubator/gpu-speedups and gave you write access. Let me know if you have any questions. We're looking forward to having our lessons here!
