### ISSUE TITLE
NeuroImaging BIDS fMRI

### ISSUE THREAD

**Issue by jadesjardins** [carpentries-incubator/proposals#37]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
The topic is Brain Imaging Data Structure (BIDS) standardization for functional Magnetic Resonance Imaging (fMRI). This is part of a larger set of "NeuroImaging" material that is being developed in conjunction with the Canadian Open Neuroscience Platform (CONP).

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes: https://github.com/conp-pcno-training/SDC-BIDS-fMRI 

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
Yes.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 
Yes.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
NA.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 
Yes.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 
jerdra, josephmje, jadesjardins

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
Thank you @jadesjardins! Sorry for the delayed response. I'll work on getting your materials transferred over to the Incubator this week and let you know if I have any questions.

**Comment by jadesjardins** [comment]
Hi Erin! No need to apologize (trust me.. I would not have been able to response if you had followed up sooner!).
Question: We have a group that is developing several lesson module under the umbrella of "BrainImaging". Is there a way that we could start adding all of these proposals under a named "BrainImaging" project within carpentries-incubator/proposals? I think that this would help us stay organized.. and help other potential contributors navigate the overall effort to establishing the BrainImaging materials.

**Comment by ErinBecker** [comment]
@jadesjardins - Thanks for the understanding 😄 

One question back to you before we get these materials transfered. It looks like the link you shared is a fork of https://github.com/TIGRLab/2019-05-27-fmri-python. We'd like all incubator lessons to be parent repositories, to avoid issues down the line. Could you please use the [GitHub Importer](https://github.com/new/import) to import your materials as a new parent repository? To transfer the materials, you'll need to accept the invitation I just sent to join the carpentries-incubator GH organisation. If you don't see that invitation in your inbox, please let me know. After you accept that invite, you should have permission to transfer your lesson materials into the incubator. (Settings (all the way at the bottom, in the Danger Zone) --> Transfer). Let me know if you have any questions about this process. 

About your question: 

> Question: We have a group that is developing several lesson module under the umbrella of "BrainImaging". Is there a way that we could start adding all of these proposals under a named "BrainImaging" project within carpentries-incubator/proposals? I think that this would help us stay organized.. and help other potential contributors navigate the overall effort to establishing the BrainImaging materials.

I haven't used the "Projects" feature of GH before. Is this what you're referring to (["About project boards"](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards)? Or were you thinking more generally of having some sort of tagging system to link together these different lesson repos in the "BrainImaging" umbrella? I'm not sure how to do this. Looking up "how to organise GitHub repositories" brings up recommendations to create organisations, but I'm not sure we could put these repos into a different organisation and still have them show up on the [Community Lessons page](https://carpentries.org/community-lessons/). There's also the possibility of [repository topics](https://github.com/orgs/carpentries-incubator/topics), but there doesn't appear to be any way to sort or filter repos within an organisation by topic. I think what you're proposing is a great idea, I'm just not sure how to implement it. Any ideas? 

Another (inelegant) possibility is naming all of the BrainImaging repos to reflect that they're part of this collection (e.g. "BrainImaging-fMRI). Would love to hear your thoughts on this or alternatives.

**Comment by jadesjardins** [comment]
Hi Erin,
Very sorry that I went AWOL again. I missed the invitation that you sent me (to re-import the fMRI repo) and let it expire. Could you resend it to me?
Also, I have started looking to the github "Projects" to see if this could help with the organization/coordination of the various "BrainImaging" repos that are currently being developed and scheduled to be imported to the Carpentries Incubator. I am not sure if this will be the appropriate solution yet. I am going to recommend that we import them all individually as they are for now and explore methods for organizing as a "BrainImaging" set later.
James

**Comment by fmichonneau** [comment]
@jadesjardins I just re-sent you the invitation. Importing the different repos at this time would work well. Thanks!

**Comment by ErinBecker** [comment]
Thanks @fmichonneau for resending! @jadesjardins - I see that the SDC-BIDS-IntroMRI and SDC-BIDS-dMRI repos are now in the Incubator. I don't see them showing up yet on the [Community Developed Lessons](https://carpentries.org/community-lessons/) page, but I think that's just a function of them not having the right tags. I'll tag them now and then check if they show up on the page. If so, I'll go ahead and close this issue!

**Comment by ErinBecker** [comment]
@jadesjardins - I'm following up to confirm that yes, these lesson do now appear on the Community Developed Lessons page. 

A couple of small (?) followups: 
1) Right now, both lessons are showing up with the same title ("Introduction to MRI and BIDS") so I recommend changing one or more of the lesson titles (the Community lessons page pulls from the GH repo description). 

2) I'm working to standardize team settings across all incubator repos. Would it be appropriate for me to change the settings for the [BrainImaging team](https://github.com/orgs/carpentries-incubator/teams/brainimaging-maintainers/repositories) from "Read" to "Maintain"? If you'd rather not have everyone have this level of access, that's ok, just please let me know.

3) The repos in the incubator appear to be forks. Due to the nuances of how GH manages forks vs imports, we'd prefer to have these imported or directly transferred so that the canonical repo lives within the incubator repository. The optimal solution for this depends on where you anticipate future development to happen. If you expect that development to happen within the Incubator, I would recommend transferring the repo ownership. You would have "Maintain" access to that repo, which should also enable you to add or remove collaborators and fine tune access as needed. Please let me know what you would like to do.

**Comment by jadesjardins** [comment]
Hi Erin,

Responses below...

On 2020-06-30 3:35 p.m., Erin Becker wrote:
>
> @jadesjardins <https://github.com/jadesjardins> - I'm following up to 
> confirm that yes, these lesson do now appear on the Community 
> Developed Lessons page.
>
> A couple of small (?) followups:
>
> 1.
>
>     Right now, both lessons are showing up with the same title
>     ("Introduction to MRI and BIDS") so I recommend changing one or
>     more of the lesson titles (the Community lessons page pulls from
>     the GH repo description).
>
I will change the name of the dMRI lesson.
>
> 1.
>
>     I'm working to standardize team settings across all incubator
>     repos. Would it be appropriate for me to change the settings for
>     the BrainImaging team
>     <https://github.com/orgs/carpentries-incubator/teams/brainimaging-maintainers/repositories>
>     from "Read" to "Maintain"? If you'd rather not have everyone have
>     this level of access, that's ok, just please let me know.
>
Changing to "Maintain" sounds good.
>
> 1.
>
>     The repos in the incubator appear to be forks. Due to the nuances
>     of how GH manages forks vs imports, we'd prefer to have these
>     imported or directly transferred so that the canonical repo lives
>     within the incubator repository. The optimal solution for this
>     depends on where you anticipate future development to happen. If
>     you expect that development to happen within the Incubator, I
>     would recommend transferring the repo ownership. You would have
>     "Maintain" access to that repo, which should also enable you to
>     add or remove collaborators and fine tune access as needed. Please
>     let me know what you would like to do.
>
Can you remove https://github.com/carpentries-incubator/SDC-BIDS-dMRI 
and https://github.com/carpentries-incubator/SDC-BIDS-IntroMRI ? Then I 
will re-import them from the origin instead of the fork.

**Comment by ErinBecker** [comment]
Perfect. Thanks for the quick response @jadesjardins. I've deleted those two repos. Once you've re-imported them, I'll adjust the access settings to "Maintain" and add the correct tags back on so it renders properly on the community lessons page.

**Comment by tobyhodges** [comment]
This looks like it was taken care of, so I'm closing this Issue. Please post back here if there's still a reason to keep it open and I'll be happy to reopen.
