### ISSUE TITLE
R for survival analysis (and more)

### ISSUE THREAD

**Issue by lauzikaite** [carpentries-incubator/proposals#38]
I'm sharing existing materials that we have been using during our 2-day introductory workshops to R.

1. What is the topic of your lesson or lesson proposal?
The goal of this lesson is to practice the common methods for data manipulation and visualisation, as well as survival analyses using the mortality dataset of the Game of Thrones series. It is designed to be taught at the end of a 2-day introductory workshop to R.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes
https://lauzikaite.github.io/r-survival-analysis/

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 
Yes and Yes

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 
Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 
Not sure yet

8. Any other information you would like us to have or questions you have for us?

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
Wow! Cool dataset @lauzikaite! I'll work on transferring this material this week and let you know if I have any questions.

**Comment by ErinBecker** [comment]
@lauzikaite - you should have just received an invitation to join the carpentries-incubator GH organisation. After you accept that invite, you should have permission to transfer your lesson materials into the incubator (Settings (all the way at the bottom, in the Danger Zone) --> Transfer). Let me know if you have any questions!

**Comment by lauzikaite** [comment]
@ErinBecker, transfer is done. 
Can you point me to documentation on how can I continue contributing to this lesson? I am not sure if it's true a fork and directly? At the moment, I just want to modify the website link so that our team could keep using the materials with students. Thanks!

**Comment by fmichonneau** [comment]
Hi @lauzikaite 

You have admin access to the repo at the new location.

You can update the URL for your remote, in the directory where your lesson lives on your system:

```git
git remote set-url origin https://github.com/carpentries-incubator/r-survival-analysis.git
```

(if you're remote is called origin and you use the https protocol)

and then you can pull/push as usual.

Let us know if you have any questions.

**Comment by ErinBecker** [comment]
Thanks @fmichonneau for answering @lauzikaite's questions. Please let us know if you have any other questions. :-)
