### ISSUE TITLE
Issue template out of date

### ISSUE THREAD

**Issue by ErinBecker** [carpentries-incubator/proposals#40]
From @zkamvar  - 

> As a side note on the issue template, GitHub has moved to a new, more convoluted system of staging issue templates (where you can specify different templates for different scenarios) and it gives a warning in the preview that this issue template is out of date: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates

**Comment by fmichonneau** [comment]
I'd like to keep the old format, as the new format (at least in my tests a few months ago) would require an additional click before people interested in submitting a new lesson would see the template. Closing now, but feel free to re-open if you think the other format would be better.
