### ISSUE TITLE
Data Carpentry for Business (Python module)

### ISSUE THREAD

**Issue by davis68** [carpentries-incubator/proposals#42]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

**Python for business applications**

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

**Yes, https://github.com/data-lessons/python-business/**

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

**Yes**

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

**Yes**

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

**Yes**

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

**ProfessorBrunner**, **davis68** (maintainer), **zllu2**

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
Hi Neal - thanks for submitting your lesson (I love the waffle cat). I've gone ahead and transferred the lesson to the Incubator and you should now see it rendered at https://carpentries-incubator.github.io/python-business/.  Within the next 24 hours, it should also appear on the [Community Developed Lessons](https://carpentries.org/community-lessons/) page. 

I've also sent you an invitation to join the carpentries-incubator GH org as a member. Once you accept that invitation, I'll be able to give you Maintainer access to the transferred repository. 

Please let me know if you have any questions and thanks again!
