### ISSUE TITLE
Data Science for Doctors

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/proposals#44]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Data science for doctors by @docsteveharris, https://github.com/docsteveharris.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
http://datascibc.org/Data-Science-for-Docs/

Not sure about the source code repository, would have to ask the owner Steve Harris.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
I believe so.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
I believe they use the old Carpentries lesson template but would benefit of converting to the new one. Not sure where the source code repo is, would have to ask the owner.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
Probably not, would have to ask the owner.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 
Probably not, would have to ask the owner (https://github.com/docsteveharris)

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by anenadic** [comment]
I have a feeling I have submitted this material here once already but could not find it. So here it is again :-).

**Comment by tobyhodges** [comment]
Hi @anenadic ! Thanks for providing this information. It seems like you're recalling #22, which was closed after [this repository](https://github.com/carpentries-incubator/Data-Science-for-Docs) was created in the Incubator. Edward Palmer and Steve Harris are maintainers on that repository. Please let me know if you need any more information or if I can assist in any other way with this.

**Comment by anenadic** [comment]
Duuh, thank you @tobyhodges - I had a feeling Steve or I already submitted it in the past but could not find the repo. Closing the issue.
