### ISSUE TITLE
Data Organization for Camera Trap Images

### ISSUE THREAD

**Issue by evebohnett** [carpentries-incubator/proposals#46]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Data Organization for Camera Trap Images
2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Here's an outline
Introduction to camTrapR
Introduction to Microsoft's Megadetector
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for the lesson suggestion, @evebohnett. It sounds like it could be really useful for many researchers. Please let me know if you'd like me to create a repository for this lesson in the Incubator, so you and/or others can begin working on materials.

**Comment by evebohnett** [comment]
Thanks. I'm down for helping to start the process. Data Carpentry for Camera Traps
Best,
Eve Bohnett



 

    On Monday, August 24, 2020, 04:08:28 AM EDT, Toby Hodges <notifications@github.com> wrote:  
 
 


Thank you for the lesson suggestion, @evebohnett. It sounds like it could be really useful for many researchers. Please let me know if you'd like me to create a repository for this lesson in the Incubator, so you and/or others can begin working on materials.

**Comment by tobyhodges** [comment]
@evebohnett that's great to hear! You should have received invitations to join **carpentries-incubator** and the blank slate repo (https://github.com/carpentries-incubator/camera-traps/) for the lesson. The lesson pages are being served at https://carpentries-incubator.github.io/camera-traps/ If you're not sure where to start with developing the lesson, there's a checklist of suggested first steps in the [README](https://github.com/carpentries-incubator/camera-traps/blob/gh-pages/README.md)

I'll close this issue now but, if you have any questions or run into any trouble, please feel free to re-open it and post here, or reach out to me by email/Slack. I'd like to chat soon to find out more about your plans for the lesson and how I can support you while you're developing the material - I'll be in touch by email in the next day or so.
