### ISSUE TITLE
Promote the page with lessons more

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries-incubator/proposals#48]
Hi! I love the incubator/lab, but every time I want to find the list of lessons, I struggle. The url is https://carpentries.org/community-lessons, but it is not mentioned very often - most links go to the readme of this repo. On carpentries.org only https://carpentries.org/learn/ links to it, as far as I can tell. Why not link from https://carpentries.org/workshops-curricula/? Also, this repo could have it as url on the landing page...

**Comment by ErinBecker** [comment]
Thanks for this issue @lexnederbragt. I completely agree that the community lessons page needs more visibility. We have a new full-time member of the Curriculum Team joining in under two weeks (17 August) who will be putting all of their time towards Incubator/Lab work. I'll tag this issue for follow up by them when they start. 😄

**Comment by wallacelab** [comment]
Quick and easy fix: Link to https://carpentries.org/community-lessons in the Proposals readme (ideally near the top). I just had the same issue, and navigating up to the Proposals root made it look like a nearly empty repository. If I hadn't clicked on this Issue, I probably would never have found the list of lessons.

**Comment by ErinBecker** [comment]
Thanks @wallacelab. I've added that link to the top section of the readme. Leaving this issue open though as I'd like to take a closer look at how we promote and publicize the lessons page across our websites and documentation.

**Comment by tobyhodges** [comment]
Thanks for prompting this, @lexnederbragt & @wallacelab 

Addressed via https://github.com/carpentries/carpentries.org/pull/861

I'll close this now but please feel free to reopen/create a new issue if and when you identify other ways for us to promote the community developed lessons.
