### ISSUE TITLE
New Lesson - Pymarc basics for Librarians 

### ISSUE THREAD

**Issue by jayGattusoNLNZ** [carpentries-incubator/proposals#49]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

How to use the Python library 'pymarc' to engage with library records in MARC format 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://github.com/jayGattusoNLNZ/pymarc_basics 

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

jayGattusoNLNZ

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting your materials, @jayGattusoNLNZ! You should have received an invitation to join the **carpentries-incubator** organisation, and a team that I've set up for collaboration on this lesson. Once you've accepted the invitation, you should be able to transfer your repository to the Incubator and continue working on it here. Please post back here once you've set the transfer going, so I can make sure that everything's set up correctly on my side, and feel free to ask if you need any more information or run into any trouble with the transfer.

**Comment by jayGattusoNLNZ** [comment]
Sweet! I moved it over... let me know if it checks out OK... 

J

**Comment by tobyhodges** [comment]
Looks good @jayGattusoNLNZ! I've added the lesson pages URL to the repository, and I'll soon update the topic tags on the repo so the lesson shows up on our [Community Lessons page](https://carpentries.org/community-lessons/). I'll close this issue now, but please reopen or get in touch with me (my GitHub username [at] carpentries [dot] org) if you need any more help. I'll reach out by email in the not-too-distant future to discuss the development of the lesson and find out more about how I and the rest of the Carpentries core team can support you.
