### ISSUE TITLE
Request addition of Snakemake Workshop to Incubator

### ISSUE THREAD

**Issue by DC23** [carpentries-incubator/proposals#50]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Data processing workflows using Snakemake.
I forked the Intro to HPC material, removed all the introductory Python (I felt these concepts were best dealt with by a separate workshop), and then expanded the Snakemake material to a full day. 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes. I have a complete workshop ready for review and testing.
https://github.com/csiro-data-school/workflows 
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
I believe so.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
Yes to both.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 
Yes, I think. By transfer, do you mean creating a fork? Or literally moving the repository from its current location?

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 
Just myself for now.

8. Any other information you would like us to have or questions you have for us?
Not at present.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hi @DC23, thanks so much for sharing this Snakemake material. I know many researchers who would find this lesson helpful.

To answer your question regarding the transfer (Q6 above): transferring the repo would indeed mean moving the location from under the **csiro-data-school** namespace to **carpentries-incubator** (this organisation). If you're happy to do that I would add you to this org, after which you could set up that transfer and keep working on the material as before in the new location.

Note that, if and when the lesson is transferred into the Incubator, I will adjust the development stage to 'alpha' to fit with the lesson life cycle as defined in [this section of the Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/the-lesson-life-cycle.html). As the material is quite complete and ready for others to try out, we would be able to get on with discussing the experience you and others have collected from teaching this material, and hopefully make quick progress towards publishing the lesson on Zenodo etc.

Please post back here to let me know how you'd like to proceed and I'll be happy to get you set up on the Incubator, and/or answer any questions you have.

**Comment by DC23** [comment]
Hi @tobyhodges ,

Thanks for your reply. Yes, I would like the lesson transferred to the incubator. Once that is complete I will fork it back to the CSIRO Data School so we can keep CSIRO-specific modifications there (mostly to setup and cluster access instructions).

Resetting back to Alpha seems perfectly appropriate. 

Cheers,
Daniel

**Comment by tobyhodges** [comment]
Thanks @DC23. I've invited you to join the **carpentries-incubator** organisation, after which you can initiate the repo transfer from the settings page of your current repository. If you'd like to adjust the lifecycle stage after you've done that, please go ahead. Otherwise, I can do it for you at the same time as I set the topic tags on the repository so the lesson gets listed on our [Community Lessons page](https://carpentries.org/community-lessons/). Please post back here if you have any trouble or with questions and I'll do my best to help.

**Comment by DC23** [comment]
Hi @tobyhodges, my apologies but can you please resend the incubator invite? Things have been crazy at work and I overlooked the invite. It has now expired.

**Comment by tobyhodges** [comment]
✅ I've resent the invitation, @DC23

**Comment by tobyhodges** [comment]
Closed after [the lesson was transferred into the Incubator](https://github.com/carpentries-incubator/workflows)
