### ISSUE TITLE
Introduction to TEI (XML metadata and transcriptions)

### ISSUE THREAD

**Issue by PhilReedData** [carpentries-incubator/proposals#51]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
**Introduction to TEI**

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)
**Yes**: https://uomlibrary.github.io/workshop-tei/

3. Do your materials conform to our [Code of Conduct][coc]?
**Yes**

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
**Yes and yes**: https://github.com/UoMLibrary/workshop-tei

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
**N/A**

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 
**Yes**

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 
@PhilReedData @ElizabethGow @uom-nilani

8. Any other information you would like us to have or questions you have for us?
**We will be contacting the [Library Carpentry XML lesson team](https://librarycarpentry.org/lessons/) and invite them to contribute.**

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hi @PhilReedData, thanks for sharing this TEI lesson material! I'd like to help you get this transferred into the Incubator: you and the collaborators you listed above should have received an invitation to join the **carpentries-incubator** organisation. Once you've accepted that invitation, you should be able to initiate the repository transfer and continue developing the lesson in its new home! 

If you're happy to go ahead with this, please post here once you've set the transfer going so I can make sure that everything's set up correctly for you on our end. Similarly, if you have any questions or run into any trouble when trying to proceed, post here and I'll do my best to help you.

**Comment by PhilReedData** [comment]
Thanks very much, @tobyhodges. It's been a while since I did a transfer, I've now successfully moved the [lessons here](https://github.com/carpentries-incubator/tei-xml) and the [new Github Pages here](https://carpentries-incubator.github.io/tei-xml/). It looks like it transferred correctly to me, but please do check if you can. 

For the next steps, is it up to me to lead here, do you have any documentation or suggestions, please?

**Comment by tobyhodges** [comment]
Fantastic - looks good to me too! I've adjusted the access settings so that the other members of the **tei-maintainers** team (@ElizabethGow and @uom-nilani) will be able to work on the repository too. If you find later that there's something you're unable to do but would like to, please get in touch and I'll be happy to help.

Regarding next steps: I don't know if you're already familiar with [the Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) but that's a good guide to the lesson development process. As the Curriculum Community Developer, I'm also here to support and advise you with all things relating to the development of new lessons in the Incubator. I suggest we try to meet online some time soon, so I can get to know you and the project a little better and we can discuss how I and the other members of the Carpentries core team can help you as you continue to develop this new lesson. I'll send you an email shortly, so that we can discuss further and hopefully agree on a date/time.

**Comment by PhilReedData** [comment]
Ah yes, of course, the handbook, thank you. I also missed an opportunity to do some maintainer on-boarding this year, I think that will happen again in January for LC (though I will look out for other calls too). 

I will take you up on your offer of a meeting, might be late September by the time we can regroup at our end (I will consult with some people who don't use GitHub too).

**Comment by tobyhodges** [comment]
Thanks, I've sent an email to the address we have for you in the Carpentries database. Looking forward to chatting more about this. I'll close this issue now, but please feel free to get in touch if you hit any obstacles further down the line.
