### ISSUE TITLE
Singularity Introduction

### ISSUE THREAD

**Issue by jcohen02** [carpentries-incubator/proposals#54]
> 1. What is the topic of your lesson or lesson proposal?

Introduction to [Singularity](https://github.com/hpcng/singularity)

>2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes. The material is available as episodes [11](https://imperialcollegelondon.github.io/2020-07-13-Containers-Online/09-singularity-gettingstarted/index.html), [12](https://imperialcollegelondon.github.io/2020-07-13-Containers-Online/10-singularity-containers/index.html), [14](https://imperialcollegelondon.github.io/2020-07-13-Containers-Online/11-singularity-images/index.html) and [16](https://imperialcollegelondon.github.io/2020-07-13-Containers-Online/12-singularity-mpi/index.html) of this [course repository](https://github.com/ImperialCollegeLondon/2020-07-13-Containers-Online). Note that this material was developed as an "add on" to the [Docker material](https://github.com/carpentries-incubator/docker-introduction) discussed in issue #18. We feel that this would fit better as a separate lesson that could be taught in combination with or indepdendently to the Docker material.

>3. Do your materials conform to our [Code of Conduct][coc]?

Yes, as far as I'm aware.

>4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes and yes.

>5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

>6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository.

Since the material is currently bundled in with episodes of Docker material, if you're happy to accept this into the incubator and would be able to create a new repository (e.g. singularity-introduction), I would then open a PR to pull in the relevant sections of the material. Alternatively, I can create a new repo myself, do this work locally and then transfer the repo.

> 7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

@jcohen02
@aturner-epcc
@dme26
@sstevens2

> 8. Any other information you would like us to have or questions you have for us?

> Thank you for sharing your lesson with The Carpentries community!

>[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
>[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
>[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hi @jcohen02, I'd be happy to help you get these materials into the Incubator as a new lesson. I propose to create a repository for you here, containing the Carpentries template (i.e. an import of [this repository](https://github.com/carpentries/styles)). You could then configure the repository accordingly (set the relevant values in `_config.yml` etc - I can also help with this if you need) and merge the relevant episodes from the Docker lesson, then begin working on this as a project separate from the Docker intro. Does that sound good to you? Please post here to let me know, and/or to ask any more questions you have, and I'll keep an eye out for how I can assist you.

**Comment by jcohen02** [comment]
Hi @tobyhodges, sorry for the delay in getting back to you but yes, this all sounds good and thanks for the offer of assistance. I assume that since the material is already using the Carpentries template, once you've set up the new repository as an import of the base Carpentries repo and I make the relevant updates in `_config.yml`, it should just be possible to commit the Markdown files containing the episodes and this _should_ all be quite straightforward. I can then go forward from there, updating the material as necessary.

**Comment by tobyhodges** [comment]
Great @jcohen02! I've created the repository at https://github.com/carpentries-incubator/singularity-introduction. You should have access, but please post here if you have any trouble.

That repository is a "blank slate" to which you should indeed be able to add the existing Markdown episode files. I've added a general checklist to the README too, so you might want to look through that and delete the section when you update the content to be more lesson-specific. I'll close this Issue now, but please feel free to post back here and reopen it if you run into any difficulty or if you'd like to ask anything else relating to transferring the Singularity lesson material.

**Comment by jcohen02** [comment]
Hi @tobyhodges, I've prepared the Singularity material for an initial import into the [singularity-introduction](https://github.com/carpentries-incubator/singularity-introduction) repo. I've made a few edits to disconnect the material somewhat from the docker material that it was originally integrated with and I've also updated the other repository metadata files so things should be ready to go.

I've done this in a branch and my intention was to push the branch directly to the singularity-introduction repo and then create a PR in case you wanted to check things and also to provide some provenance information for the import of the initial content. I'm assuming as a maintainer that I should have write access to the repo and I should have been able to push my branch directly rather than creating it in a fork however I'm getting a permission denied response from GitHub. Is there something up with the permissions? I can push my updates to a fork and raise the PR that way if this is the preferred approach.

Thanks.

**Comment by tobyhodges** [comment]
Thanks for the reminder, @jcohen02: I forgot to update the access levels when I created the repository. I've done that now and I hope you can now push your branch directly to https://github.com/carpentries-incubator/singularity-introduction 

Please give that a try and post back here to let me know how you get on. For now I'll reopen this Issue, so I don't forget to watch out for updates...

**Comment by jcohen02** [comment]
Many thanks @tobyhodges, this all looks good now - I've pushed the branch and opened a [PR](https://github.com/carpentries-incubator/singularity-introduction/pull/1). 

I haven't merged yet in case you wanted to check the material first but if you're happy for me to just go ahead and merge, I'll do so. I've also added a couple of issues that you may be able to offer some advice on?

**Comment by tobyhodges** [comment]
Great to see this, @jcohen02! It looks great to me and I'm very happy to see that @sstevens2 reviewed the PR. I'm going to close this Issue now but please don't hesitate to get in touch if you have any questions or run into any trouble. I'll be in touch again by email to discuss more about how I and the rest of the core team can support you in the development of the Singularity lesson.
