### ISSUE TITLE
Analysis and interpretation of bulk RNA sequencing data using Bioconductor

### ISSUE THREAD

**Issue by csoneson** [carpentries-incubator/proposals#58]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

`Analysis and interpretation of bulk RNA sequencing data using Bioconductor` shows how to use Bioconductor packages to analyse RNA-Seq data. The target audience would be users familiar with R and Bioconductor.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Not in an adapted form, but it will likely share features with existing [workflows](https://www.bioconductor.org/packages/release/workflows/html/rnaseqGene.html).

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

No

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes - please name it `bioc-rnaseq`

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

csoneson, jdrnevich

8. Any other information you would like us to have or questions you have for us?

This lesson would be the third lesson in an effort to develop Carpentry-style Bioconductor lessons.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks @csoneson. You and @jdrnevich should have received an invitation to join the **carpentries-incubator** organisation and the team of developers for this new lesson. I've created the "blank slate" repository for this lesson here: https://github.com/carpentries-incubator/bioc-rnaseq

The README of that repository includes some instructions to get you started with creating the lesson. If you get stuck or would like any more information about anything relating to the Carpentries Incubator, lesson development, the lesson template, etc, please tag me in an Issue on the repository or contact me directly by email/Slack.
