### ISSUE TITLE
Materials to teach and learn the Julia programming language

### ISSUE THREAD

**Issue by SaranjeetKaur** [carpentries-incubator/proposals#59]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Answer: `Exploring the Julia language` : This is the main topic. The material shall have lessons on different sub-topics.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Answer: Not yet.
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
Answer: I shall take due care that the materials conform to the Code of Conduct, when I share the lessons here.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
Answer: They are not yet on GitHub.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
Answer: Yes, it would be very helpful to have a repository created in The Carpentries Incubator, please name it as `julia-materials`

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 
Answer: I don't know how to answer this question as of now.

8. Any other information you would like us to have or questions you have for us?
Answer: Can those who are not part of Carpentries, be invited to help develop and/or contribute to these lessons. If so, how should I invite them or will this be done by The Carpentries Incubator Team?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hi @SaranjeetKaur, thank you for submitting this proposal. I'd be very excited to see lesson material on Julia included in The Carpentries Incubator!

> Can those who are not part of Carpentries, be invited to help develop and/or contribute to these lessons. If so, how should I invite them or will this be done by The Carpentries Incubator Team?

Lesson developers do not need to be certified Carpentries Instructors but we do require that developers abide by our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view). Additionally, we strongly encourage those developing lessons here to follow the principles of good lesson design that we introduce during Instructor Training. If your collaborators are unfamiliar with this approach I recommend you refer them to the [Curriculum Development Handbook](https://cdh.carpentries.org/), which serves a guide through reverse lesson design.

 If you know the GitHub usernames of the people you'd plan to collaborate with on this lesson, you can post them here and I can add them to a Team of developers when the lesson repository is set up. But you will also be able to invite them yourself later, so don't worry if you can't provide that information now.

Before I proceed, I have a question about the lesson(s) you have planned. In your lesson proposal, you wrote

> The material shall have lessons on different sub-topics.

Does this mean you intend to create multiple lessons in separate repositories? (e.g. Like Software Carpentry has separate [Shell](http://swcarpentry.github.io/shell-novice/), [Python](https://swcarpentry.github.io/python-novice-inflammation/), [R](https://swcarpentry.github.io/r-novice-inflammation/), and [Git](https://swcarpentry.github.io/git-novice/) lessons?) Or are you referring to separate sections of a single lesson? (e.g. Like [the Data Carpentry "Data Analysis and Visualization in R for Ecologists" lesson](https://datacarpentry.org/R-ecology-lesson/index.html) has episodes on [Intro to R](https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html), [Starting with Data](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html), [Manipulating Data](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html), and so on?)

**Comment by SaranjeetKaur** [comment]
Thank you so much for your comment!

I would need a single repository, in which I will create separate sections: for each sub-topic.

As of now, I don't know the GitHub usernames of those who can potentially be a part of these materials. Will progress on this front with time. And take care that they abide by the Code of Conduct and refer the Curriculum Development Handbook.

**Comment by SaranjeetKaur** [comment]
Later on we might need more repositories. However, I'm unable to see the need for more than one repository at the moment.

**Comment by tobyhodges** [comment]
Okay, excellent. Thanks for the swift response. We're almost ready to go then. 

I'd prefer to choose a name more specific than `julia-materials` for the lesson. This will help us make a distinction between Julia lessons in case you or someone else chooses to develop another lesson about Julia, for another topic that doesn't fit with this one.) **Would you be happy with `julia-novice`?** This would be consistent with the `shell-novice`/`python-novice-*`/`git-novice` naming convention used in Software Carpentry lessons.

**Comment by SaranjeetKaur** [comment]
`julia-novice` sounds good!

**Comment by tobyhodges** [comment]
@SaranjeetKaur You should have received invitations to join [the repository](https://github.com/carpentries-incubator/julia-novice) and the Team I've set up for you to add collaborators to in the future. I'll also add some topic tags to that repository, so your new lesson appears on our [Community Developed Lessons page](). You might find that other community members reach out to you as potential collaborators after they find out about the lesson there.

I'd love to learn more about your plans for the lesson and discuss ways in which I and the rest of The Carpentries core team can support you as you develop the material. If that's a conversation you'd like to have, please send me an email (my GitHub username + @carpentries.org).

**Comment by SaranjeetKaur** [comment]
Thank you so much @tobyhodges ! Will definitely keep you updated on this front.

**Comment by logankilpatrick** [comment]
Hey all, happy to help on this front!

**Comment by SaranjeetKaur** [comment]
Great to have you here @logankilpatrick ! 😊

**Comment by kescobo** [comment]
I would also be happy to get in on this, or (if desired) a parallel Data Carpentry curriculum in julia. I applied for instructor training and will complete as soon as is feasible - please let me know how I can support this effort :+1:

**Comment by SaranjeetKaur** [comment]
Glad to have you here @kescobo !

**Comment by jd-foster** [comment]
I would work on this, working with @kescobo on a parallel but integrated approach in the Data Carpentry curriculum, as part of a Study Group facilitated by @tobyhodges 
Thanks

**Comment by tobyhodges** [comment]
@jd-foster @kescobo For the sake of our record-keeping, please could one of you open a new issue here proposing the DC Julia lesson. You can keep the issue very brief, mentioning this issue thread (#59), and I will get on with creating a new lesson repository for you to begin working on.
