### ISSUE TITLE
SQL for Business

### ISSUE THREAD

**Issue by davis68** [carpentries-incubator/proposals#60]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

SQL for business applications

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://github.com/data-lessons/sql-business

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes, yes.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes anyway.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

davis68, ProfessorBrunner, elliewix, ariapn

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks @davis68 we'd love to include this lesson in The Carpentries Incubator. I've created a Team for the maintainers you listed above, and you can go ahead and transfer the repository into the **carpentries-incubator** organization whenever you're ready. Once that's done, I'll make sure everything's set up correctly on our side e.g. for the lesson to be listed on the [Community Developed Lessons](https://carpentries.org/community-lessons/) page.

Please post back here if you have any questions or run into any trouble with the repository transfer.

**Comment by tobyhodges** [comment]
Thanks for making the transfer, @davis68. I've updated the repository topic tags so it shoudl show up on the Community Developed Lessons page in the next 24 hours. I'll close this Issue now but feel free to re-open and post back here if you need any more help getting set up to continue development on this lesson in the Incubator.
