### ISSUE TITLE
Text Analysis with Python

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/proposals#62]
1. What is the topic of your lesson or lesson proposal?

Learning python and some beginning of text analysis (with nltk) for digital humanities

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No, but we have started drafting learning objectives and the lesson outline.  We were hoping to set up a repo here to start putting the lesson together.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by sstevens2** [comment]
cc: @claremichaud

**Comment by tobyhodges** [comment]
Thanks for the lesson proposal, @sstevens2! I can set up a "blank slate" repository for the lesson in The Incubator and give you Admin access to take care of the further development. Is there anyone else you'd like to be included in the maintainer team for this lesson?

**Comment by sstevens2** [comment]
Thanks @tobyhodges!  I know @claremichaud will need to be a maintainer but don't have github ID's for the other folks who will be helping yet.   Can I reach out later when I have the list?

**Comment by tobyhodges** [comment]
Great, thank you @sstevens2 - I've created the blank lesson repository at https://github.com/carpentries-incubator/python-text-analysis

@claremichaud is on the maintainer team and I've granted you Admin access to the repository, so you can add other collaborators yourself. But I'll also be happy to do so if and when you know the GitHub handles of your other collaborators.

I'm going to close this issue now, but please post back here and re-open it if you have any trouble getting started on the lesson.

**Comment by sstevens2** [comment]
Thanks for setting up the repo and permissions @tobyhodges!  I'll reach out if I have any questions but I'm happy to add the collaborators myself.
