### ISSUE TITLE
Parallel Programming in Python

### ISSUE THREAD

**Issue by jhidding** [carpentries-incubator/proposals#63]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
    - Parallel Programming in Python, discussing `multiprocessing`, `threading`, profiling using `%timeit`, memory profiling, `dask`, the GIL, `numba` and more. The goal is to teach not just how to use Dask, but the major concepts going into parallel programming and how it changes the way you design code.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
    - Yes, [github:escience-academy/lesson-parallel-python](https://github.com/escience-academy/lesson-parallel-python)

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
    - To my best knowledge it does.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
    - Yes and yes.

~5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?~

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
    - That would be up for discussion with Netherlands eScience Center, but I see no major objection.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
    - At least: @jhidding @mkuzak

8. Any other information you would like us to have or questions you have for us?
    - Nope

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting this proposal, @jhidding I think the lesson is very relevant to many in our community. I'll invite you to the carpentries-incubator organization so that you can transfer the repository into the Incubator, but need to mention one thing to take care of afterwards: once in The Carpentries Incubator, the lesson pages should use the Incubator theme (set in `_config.yml` with `carpentry: incubator`). This is probably a good time to update the lesson to use our remote theme (add `remote_theme: carpentries/carpentries-theme` to `_config.yml` and remove the `_includes`, `_layouts` and `assets` directories from your repository), which will save you future work to stay up-to-date with the latest changes to the theme. I'll be happy to prepare a PR to make those changes if you prefer.

**Comment by jhidding** [comment]
I tried to do that but things fail to build now (in the incubator branch). There are some unmerged pull requests that I'd like to resolve with our team before I transfer ownership (we'll get to it on Friday).

**Comment by tobyhodges** [comment]
Thanks for [transferring the lesson over](https://github.com/carpentries-incubator/lesson-parallel-python), @jhidding! I'm going to close this issue now, but please post back here or tag me in an issue on the lesson repository if you have any questions or need any help.
