### ISSUE TITLE
Good Enough Practices

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/proposals#64]
1. What is the topic of your lesson or lesson proposal?

**Good Enough Practices in Scientific Computing.** It is the 3 hour carpentries format version of [Good Enough Practices in Scientific Computing](https://doi.org/10.1371/journal.pcbi.1005510): "a set of good computing practices that every researcher can adopt, regardless of their current level of computational skill". It is absolutely entry level - if you like, material to motivate learners to attend their first skills-focused carpentries workshop. We have already delivered a version of this as a workshop to new PhD students in Edinburgh, where it has been well received. In 3 hours you can mostly cover motivation and organisation, and encourage learners to share stories and experiences of why the advocated approaches are needed. We have had feedback when teaching [software carpentry git novice](https://swcarpentry.github.io/git-novice/) that some learners didn't quite understand what git was for. The proposed lesson offers that missing ingredient, and so could be offered in a package before the git workshop.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

There's a [powerpoint slideshow version](https://uoe-my.sharepoint.com/:p:/g/personal/ewallac2_ed_ac_uk/EXg_Be-2K9pHmDTJXT-qDtcB0XS5DaeC2FSavhIj1T73Gw?e=DRflur). This has discussion points and prompts indicated, that can be adapted into discussions for the carpentries lesson template.

3. Do your materials conform to our [Code of Conduct][coc]?

Yes.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

We have created a carpentries lesson template repository at [/edcarp/good-enough-practices](/edcarp/good-enough-practices). As I write, that is an empty placeholder, but it is where we will build the lesson.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

N/A

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

We have a team of volunteers from [Edinburgh Carpentries](https://edcarp.github.io/): @ewallace, @ppxasjsm, @JenDaub, @npch, @davemckain, @mhagdorn, @Lucia-Michielin.

8. Any other information you would like us to have or questions you have for us?

We discussed this lesson idea on twitter with @tracykteal and @lexnederbragt, who seemed enthusiastic.

We are writing a grant application in Edinburgh that would involve more material being developed for submission to Carpentries incubator, so we should talk about that elsewhere.

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks @ewallace, this lesson idea seems very appropriate for The Carpentries! 

You should have received an invitation to join the carpentries-incubator organization. After you've accepted that, you can transfer the repository over to the Incubator and continue developing the lesson here. I will set the relevant topics on the repository, to make sure that it appears on our [Community Developed Lessons](https://carpentries.org/community-lessons) page.

I've also invited the collaborators you mentioned, so they should all be able to join the team I created for maintainers of this lesson. Please ping me here if you have any questions or if something doesn't seem to be working, and let me know if/when the repository transfer has been completed.

**Comment by ewallace** [comment]
Thanks @tobyhodges. Our grant to work on this has just started. We have added @aromanowski, @tzielins, to the team. We will work on transferring the repo to the incubator soon and map out a development plan.

**Comment by tobyhodges** [comment]
Excellent. Thanks for the update, @ewallace! Please post a link here when the transfer is done, and I will close the issue.

**Comment by ewallace** [comment]
Hi. Given we had only really made a "shell" repository using the carpentries lesson template back in October 2020, we are wondering if it is more sensible to start a brand new repo from the current lesson template, at carpentries-incubator/good-enough-practices?

@tobyhodges it would be good to get your opinion on this? Or @gperu will follow-up with the team.

**Comment by ewallace** [comment]
@tobyhodges sorry we've been slow here. Would your team be able to initialize a new repository using current Carpentries template, at [/carpentries-incubator/good-enough-practices](/carpentries-incubator/good-enough-practices)? Then we can start to develop and add content there, and delete the previous placeholder repo.

Thanks!

**Comment by tobyhodges** [comment]
Hey @ewallace Sorry I missed that you asked me a question in your last reply. I have created the repository at https://github.com/carpentries-incubator/good-enough-practices and granted you and the Maintainer team access.

I will close this issue now that the repo has been set up, but please feel free to post back here if you have any further questions.

Finally, here is some info for you and your collaborators about how you can stay in touch with The Carpentries curriculum community: you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member). And you might consider adding the repository to be listed on [the Help Wanted page](https://carpentries.org/help-wanted-issues/) so that any issues you label `help-wanted` will show up there for the wider community, e.g. checking out trainee instructors, to see and hopefully come and help with. The best way to do that right now is to send me an email or Slack message telling me you'd like the lesson incldued on that page, and I will get it added.

**Comment by ewallace** [comment]
Magnificent, thanks. We will get started here then.
