### ISSUE TITLE
Analysis of Microbial Amplicon Data

### ISSUE THREAD

**Issue by wallacelab** [carpentries-incubator/proposals#66]
1. What is the topic of your lesson or lesson proposal?

Analysis of data related to microbial communities from diverse environments. Specifically, this lesson will focus on analysis of "amplicon" data made from sequencing specific short sections of DNA to identify which organisms are present. (This is in contrast to "shotgun" metagenomics, which looks at all DNA and which already has [a Carpentries Incubator lesson](https://carpentries-incubator.github.io/metagenomics/) in alpha stage.) The main topics will be (1) Performing quality control on raw data, (2) Converting raw data into a standard table of organisms counts, and (3) Running common analyses on the count table.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
No. (We have initial planning in the 'dc-microbiome' channel in the Carpentries' Slack workspace.)

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

**Comment by tobyhodges** [comment]
Hi @wallacelab thanks for submitting this lesson idea. I think it would be a great fit, especially as I know you are planning to make reference to the existing shotgun metagenomics lesson where overlaps exist. 

Would you like me to create a placeholder repository for this lesson in The Carpentries Incubator? I would then invite you to join the *carpentries-incubator* organisation and give you Admin access to the repository so you can begin developing the lesson. Additionally, if you know the GitHub usernames of those who will be collaborating with you on the lesson, please feel free to share them here and I will make sure they get invitations to the repository too.

**Comment by wallacelab** [comment]
Thank you. And yes, please create a placeholder that we can start working on. I’ve reached out to other folks and I assume I can add them later if need be.

-Jason


Jason Wallace
University of Georgia | Department of Crop & Soil Sciences
jason.wallace@uga.edu<mailto:jason.wallace@uga.edu> | 706-542-9696<tel:7065429696>
wallacelab.uga.edu<https://wallacelab.uga.edu/> | Twitter<https://twitter.com/thewallacelab> | Instagram<https://www.instagram.com/thewallacelab>

**Comment by tobyhodges** [comment]
Great! The lesson repository is now set up at https://github.com/carpentries-incubator/microbial-amplicon-analysis and you should have received invitations to join the repository, the lesson maintainer team, and the carpentries-incubator organisation. You're right - as Admin on the repository you can invite anyone else you want to grant access to.

When you get started on developing your lesson, I recommend checking out [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/), which gives some guidance on good practices in lesson design, and [the Lesson Example](https://carpentries.github.io/lesson-example/), which provides a good guide to using The Carpentries lesson template.

I will close this issue now, but please feel free to reopen it or ping me (@tobyhodges) in an issue on the lesson repository if you run into any problems or have any questions about how to proceed from here. Looking forward to seeing what you do with the lesson!
