### ISSUE TITLE
Statistical analysis for public health

### ISSUE THREAD

**Issue by ezherman** [carpentries-incubator/proposals#67]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Statistical analysis in R for public health. This workshop, consisting of six lessons, will teach data management and analysis to learners familiar with R but lacking formal statistical training. Our current plan is to use the readily available NHANES data set (see [NHANES R documentation](https://www.rdocumentation.org/packages/NHANES/versions/2.1.0/topics/NHANES)). The workshop will cover Tidy data principles, statistical thinking, simple linear regression (incl. t-test, ANOVA and ANCOVA), logistic regression and an introduction to mixed modelling. 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hi @ezherman thanks for submitting this proposal. The lesson topic sounds very relevant to The Carpentries community and I'm happy to help you get started! I can create a repository for you in the Incubator, where you can begin developing the lesson. I will call that repository `statistics-r-public-health` unless you want to suggest a different name? 

Once the repository is set up, I will invite you to join the `carpentries-incubator` organisation on GitHub, and grant you Admin access on that repository. I can also invite any collaborators to the repository at the same time, if you share their GitHub usernames here? But no worries - you can also add them yourself later.

**Comment by ezherman** [comment]
Hi @tobyhodges thanks for responding quickly! A repository in the Incubator under the name `statistics-r-public-health` sounds great.

It would be great if you could invite my collaborators Emma Rand (@3mmaRand) and Andrew Stewart (@ajstewartlang) to the `carpentries-incubator` organisation on GitHub as well.

Please let me know if there is anything else I can do!

**Comment by tobyhodges** [comment]
Hi @ezherman I've created the repository at https://github.com/carpentries-incubator/statistics-r-public-health and you should all have received invitations to join a Team within the `carpentries-incubator` organisation, which will give you Maintain-level access to the repository. Additionally, I have granted you, @ezherman, Admin access to the repository so you can administer it as you please. 🚀 

The README of the repository linked above includes a brief list of recommended next steps. If this will be your first time working with The Carpentries lesson template, I recommend [the Lesson Example](https://carpentries.github.io/lesson-example/) as a walk-through and reference. [The Curriculum Development Handbook](https://cdh.carpentries.org/) provides a good overview of The Carpentries approach to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development! 

I will close this issue now that the repository is created, but feel free to reopen if anything is unclear.

**Comment by ezherman** [comment]
Hi @tobyhodges, I was wondering whether I could get your thoughts on the scope of the repo. As I understand it, the repo is meant to be used for a single lesson. Our two-day workshop will consist of six lessons, taught over ~30 episodes. Do I develop all episodes in the present repo (i.e. scope of the repo is the workshop), or should I request a separate repo for each lesson? Looking at other repos in the incubator, it seems that they are used for the development of full workshops.

**Comment by tobyhodges** [comment]
Hey @ezherman if the intention is to have multiple, relatively self-contained lessons in the end, it might be best to develop in multiple repositories right away. It will probably be easier to manage the initial design/development stages (deciding what content will belong in which episode/lesson, avoiding duplication of effort/content, setting objectives for episodes, etc) if you are working on everything in a single repository. But the downside would be that, if you later split the episodes across multiple repositories you will lose the history of individual commits and contributions from multiple authors. Another advantage to multiple, individual lessons is that you can define the life cycle stage with more granularity than would be possible with One Lesson to Rule Them All.

If you already know the titles/topics of your individual lessons (and it seems that you do...), I can help you set up the separate repositories right away. We can add these additional repositories to the same Team, so you and your collaborators should immediately have access to all of them. All I would need from you is a list of suggested names for these repositories.

**Comment by ezherman** [comment]
Awesome, thank you for these details @tobyhodges. I will discuss this tomorrow with @3mmaRand and then I'll let you know!

**Comment by tobyhodges** [comment]
Sure. Feel free to reach out again if you need any more input from me during/after that discussion.

**Comment by ezherman** [comment]
Thanks @tobyhodges! It would be great if you could set up the following lesson repos:

- Statistical thinking for public health
- Simple linear regression for public health
- Multiple linear regression for public health
- Logistic regression for public health
- Linear mixed effects modelling for public health

**Comment by tobyhodges** [comment]
I will take care of that after lunch, @ezherman. For the sake of our record keeping, please could you open issues in this Proposals repository for each of these lessons? You can keep the issues extremely brief, including only the lesson title and a mention of this issue (#67), but it will help us to programmatically track the number of individual lessons proposed.

Also, I forgot to mention before, but to keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). We are just about to begin the first round of a new Lesson Development Study Groups program, so I expect to see an increase in discussion on these channels in the next few weeks.

**Comment by tobyhodges** [comment]
Here are the repositories:

- https://github.com/carpentries-incubator/statistical-thinking-public-health
- https://github.com/carpentries-incubator/simple-linear-regression-public-health
- https://github.com/carpentries-incubator/multiple-linear-regression-public-health
- https://github.com/carpentries-incubator/logistic-regression-public-health
- https://github.com/carpentries-incubator/linear-mixed-models-public-health

I have granted access to all five to you and the `statistics-r-public-health-maintainers` Team .

**Comment by ezherman** [comment]
Thank you @tobyhodges, your help has been great! I have signed up to the two groups that you suggested. Looking forward to getting involved.
