### ISSUE TITLE
Small lesson addition: Comparison of data objects in R, use of the new waldo package

### ISSUE THREAD

**Issue by AiliSarre** [carpentries-incubator/proposals#68]
1. What is the topic of your lesson or lesson proposal?

 I would like to propose a small episode or section on the use of a new R package for the comparison of objects. The purpose of the waldo package is to find and describe differences between two objects. This lesson would be small and could ideally be integrated into introductory course episodes, comparing data frames already established used in these lessons. There is only one function to learn waldo::compare(), so the main focus of the lesson would be to demonstrate its use and how to interpret the output. 

Optionally, the lesson could start with the installation of the package. Then a couple of examples of comparison of short vectors. Followed by an example of a comparison of large vectors. This would demonstrate how the output only displays the differences and not the entire vectors. Finally, an example comparing data frames. 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link. 

No draft yet.

**Comment by tobyhodges** [comment]
Hi @AiliSarre thanks for proposing this lesson idea. Data object comparison sounds like a relevant skill for The Carpentries community! Would you like me to create an empty lesson repository where you can work on this?

If you would prefer to propose this as an addition to one of The Carpentries existing R lessons, please open an issue on the relevant lesson repository and discuss it with the Maintainers.

**Comment by AiliSarre** [comment]
Hi @tobyhodges Thanks for getting back to me so quickly. Yes, please help me create a new lesson repository. Then I assume I can propose to have it integrated into an existing lesson at a later time. I am not yet sure what lesson would be most suitable. I am still new to both the Carpentries and GitHub. Thank you for helping out.

**Comment by tobyhodges** [comment]
I've created https://github.com/carpentries-incubator/r-object-comparison-waldo and invited you to join the repository and a Team for the lesson - please accept both invitations when you receive them.

As you're new to The Carpentries and GitHub, I can recommend the following resources to help get you started on the lesson:

- [The Lesson Example](https://carpentries.github.io/lesson-example/) provides an guide to the lesson template
- [The Curriculum Development Handbook](https://cdh.carpentries.org) provides an overview of our recommended approach to lesson design and development, and includes [an Appendix about developing in the Incubator](https://cdh.carpentries.org/the-carpentries-incubator.html).

You may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

And you can always ping me in this thread or on an Issue in your lesson repository if you get stuck or want more information about anything relating to The Carpentries/GitHub/lesson development. I will close this issue now that the repository is ready but please feel free to reopen it or continue posting to the thread if you want to discuss further 🚀
