### ISSUE TITLE
Workflow management with Nextflow and nf-core

### ISSUE THREAD

**Issue by ggrimes** [carpentries-incubator/proposals#74]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

**Workflow management with Nextflow and nf-core**. Nextflow is workflow engine and a domain-specific language (DSL) that eases the writing of data-intensive computational pipelines.

It is designed around the "small pieces, loosely joined" philosophy seen in Linux, whereby many simple but powerful command-line and scripting tools that, when chained together, facilitate complex data manipulations.

Nextflow extends this approach, adding the ability to define complex program interactions and a high-level parallel computational environment based on the dataflow programming model. Nextflow core features are:

*** enable workflows portability & reproducibility

*** simplify parallelization and large scale deployment

*** easily integrate existing tools, systems & industry standards

This lesson will cover the core concepts behind Nextflow and using nf-core to run community curated analysis pipelines.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No. However, I am working with the nextflow and nf-core community on migrating existing materials into the Carpentries lesson format.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

This lesson is being developed as part of the Feb 2021 Carpentries Lesson Development Study Group.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Hi @ggrimes thanks for proposing the lesson! For the Study Groups program, you will need an empty "blank slate" lesson repository, which I will set up for you now. If and when the other material you mention above is ready to be migrated into the Incubator, please create another issue/issues and we can get those transferred here too.

**Comment by tobyhodges** [comment]
@ggrimes the lesson repository is here: https://github.com/carpentries-incubator/workflows-nextflow 
You should have received two invitations: one to join a Team of maintainers for this lesson (after you have joined I will grant you access to add others to this Team if/when you have other collaborators on the lesson) and one to join the lesson repository as Admin. Please accept both.

Resources for learning about The Carpentries lesson template and good practices in lesson design/development will be introduced during the Study Groups program, so for now I will only suggest that you join [our TopicBox list for lesson developers in The Carpentries Incubator](https://carpentries.topicbox.com/groups/incubator-developers).

I will close this issue now that the repository has been created, but please feel free to reopen/post back here if you have any questions or run into any trouble accessing the repository. You can also open an issue on the lesson repository and ping me there.
