### ISSUE TITLE
SSI Machine Learning Training Course

### ISSUE THREAD

**Issue by NatePollard** [carpentries-incubator/proposals#75]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Machine Learning
2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
We do not currently have a draft. We are working under the Software Sustainability Institute grant to develop a Carpentries style Machine Learning Course. 
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
@NatePollard thank you for submitting this lesson proposal. I will create a placeholder repository for the lesson, and grant you Admin access so you can begin developing the lesson here. I will set up a Team for maintainers of the lesson repository - if you know the GitHub usernames of any collaborators you will have on the lesson, feel free to post them here and I will get them added to that Team as well. But no worries - you will also be able to add them yourself later.

I'll post back here shortly, with link to the new lesson repository.

**Comment by tobyhodges** [comment]
What would you like to be the name of the repository? I would like to include some indication of the tool/platform you will use to teach ML - something like `machine-learning-novice-python`, `machine-learning-novice-r`, `machine-learning-novice-sklearn`, and so on.

**Comment by NatePollard** [comment]
Hi Toby.  We are developing both Python and R versions of the Machine Learning course. As such can we request two repositories named: machine-learning-novice-pythonmachine-learning-novice-r Thanks, Nate. From: Toby HodgesSent: 04 February 2021 14:03To: carpentries-incubator/proposalsCc: NatePollard; MentionSubject: Re: [carpentries-incubator/proposals] SSI Machine Learning Training Course (#75) What would you like to be the name of the repository? I would like to include some indication of the tool/platform you will use to teach ML - something like machine-learning-novice-python, machine-learning-novice-r, machine-learning-novice-sklearn, and so on.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tobyhodges** [comment]
@NatePollard you should have received an invitation to join a Team for maintainers of the two lessons, and two invitations to join the repositories directly as an Admin. Please accept all of these, and you should be good to go. You are Maintainer of that Team, so you can add any collaborators you have for the lesson development, and create sub-teams for each lesson if you prefer more fine-grained control of repository access.

The repositories are here:
https://github.com/carpentries-incubator/machine-learning-novice-python
https://github.com/carpentries-incubator/machine-learning-novice-r

The READMEs of the repositories include a brief list of recommended next steps. If this will be your first time working with The Carpentries lesson template, I recommend [the Lesson Example](https://carpentries.github.io/lesson-example/) as a walk-through and reference. [The Curriculum Development Handbook](https://cdh.carpentries.org/) provides a good overview of The Carpentries approach to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). We are just about to begin the first round of a new Lesson Development Study Groups program, so I expect to see an increase in discussion on these channels in the next few weeks. 

I will close this issue now that the repository is created, but feel free to reopen if anything is unclear.

**Comment by NatePollard** [comment]
Thx Toby, I have received the machine-learning-ssi-maintainers team invite, but not the admin invite for the following repos:

https://github.com/carpentries-incubator/machine-learning-novice-python
https://github.com/carpentries-incubator/machine-learning-novice-r

I can't reopen this issue so will open a new one.
