### ISSUE TITLE
GPU Programming

### ISSUE THREAD

**Issue by isazi** [carpentries-incubator/proposals#76]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

The topic of our lesson is programming Graphics Processing Units (GPUs). We plan to develop material to teach the basics of programming these accelerators using CUDA and OpenCL.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://github.com/escience-academy/lesson-gpu-programming

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

Yes, we try to always follow the code of conduct.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes we would be willing to transfer the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@isazi @HannoSpreeuw @mkuzak

8. Any other information you would like us to have or questions you have for us?

We are currently participating in the Lesson Development Study Groups.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson proposal, @isazi. You should have received an invitation to join a maintainer Team for this lesson. After you have accepted that invitation, you should be able to transfer your lesson repository into the Incubator, ready to begin working on it in the Study Groups program.

Please post back here to tell me when you have transferred the repository, so I can close this issue, and/or to ask any questions you may have about the transfer.

**Comment by isazi** [comment]
I did accept the invitation and I have transferred our old repository to the incubator.

**Comment by tobyhodges** [comment]
Great! thanks for the swift response @isazi 👍 I will take care of a few extra bits of configuration on the lesson repository and make sure that you have all the appropriate access.

I'll close this issue now, but please feel free to post back here again if you get stuck with anything. Or you can open an issue on the repository itself and tag me there. I will do my best to respond quickly.
