### ISSUE TITLE
Data-driven research workflows in Julia

### ISSUE THREAD

**Issue by jd-foster** [carpentries-incubator/proposals#78]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
**Data-driven research workflows in Julia.** The lesson would teach basic but efficient tools and workflows in the Julia language in order help a learner progress from simply having a research data set up to the point of having ready-to-use representations of that data, whereby they would then be able to initiate scientific analysis or construct models using packages in the larger Julia package ecosystem.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
No.
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
When the materials are created, they will conform to the Carpentries Code of Conduct.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
No. The creation of new material is intended to occurring alongside The Carpentries Lesson Development Study Groups program. Please see #59.
We may also draw inspiration from past examples like https://github.com/tpoisot/julia-ecology-lesson. 

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
Yes, thanks. The core data set(s) to use in the lesson has not been identified, so the naming may be generic? Something like `julia-dc` o `julia-workflow`

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
-

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
@jd-foster @kescobo  @giordano

8. Any other information you would like us to have or questions you have for us?
This was helped along by active discussion around this on Julia Discourse, for instance, https://discourse.julialang.org/t/software-carpentry-lessons-with-julia/51996

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Than ks @jd-foster you should have received an invitation to join the carpentries-incubator organisation, via a Team set up for the developers of this lesson. The lesson repository is at https://github.com/carpentries-incubator/julia-data-workflow and I have also granted you Admin access so you have complete control over the repository from here.

You'll be introduced to the resources and processes we recommend for developing the lesson during the Study Groups program but, for now, you might find it helpful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). That Slack channel should serve as a platform for discussion across the entire Study Groups cohort.

I will close this issue now that the lesson repository is set up, but please feel free to post back here or to ping me in an issue on the lesson repository if you need help with anything.

**Comment by jd-foster** [comment]
Thank you @tobyhodges
