### ISSUE TITLE
SSI Machine Learning Training Course admin access

### ISSUE THREAD

**Issue by NatePollard** [carpentries-incubator/proposals#79]
Thx Toby, I have received the machine-learning-ssi-maintainers team invite, but not the admin invite for the following repos:

https://github.com/carpentries-incubator/machine-learning-novice-python
https://github.com/carpentries-incubator/machine-learning-novice-r

Can you set this up pls. 

Thanks, Nate.

**Comment by tobyhodges** [comment]
You are listed as an Admin on both repositories, so I'm not sure that we have a problem? Perhaps I was wrong to expect an invitation to be sent when I granted you access? Please go to https://github.com/carpentries-incubator/machine-learning-novice-r/settings/access and https://github.com/carpentries-incubator/machine-learning-novice-python/settings/access and check that you see yourself listed as an Admin.

**Comment by NatePollard** [comment]
No email was sent out, but I have checked and can confirm I have admin access. All sorted, thanks.

**Comment by tobyhodges** [comment]
good to know. and also interesting to learn that you couldn't reopen the other issue. I will have to update the instructions I give to people!
