### ISSUE TITLE
Fundamental skills for using an integrated development environment with Spyder.

### ISSUE THREAD

**Issue by map0logo** [carpentries-incubator/proposals#80]
1. What is the topic of your lesson or lesson proposal?

Use of an integrated development environment with Spyder.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes, I have a pre-alpha version of the lesson in this repo: https://github.com/qu4ntdatos/spyder4carpentries, and is rendered here https://qu4ntdatos.github.io/spyder4carpentries/

3. Do your materials conform to our [Code of Conduct][coc]?

Yes, and I am open to feedback and recommendations.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes, I like to transfer my repository to The Carpentries Incubator.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@map0logo (myself, I am a Carpentries Instructor), @ccordoba12 (Spyder Mantainer), and @juanis2112 (Spyder team)

8. Any other information you would like us to have or questions you have for us?

I believe that the proper use of some functionalities of an integrated development environment are fundamental to the productivity of researchers but are not given the attention they deserve. Even though Spyder is used as a reference, since it comes pre-installed in Anaconda and is Open Source, the idea is to work on ideas that can be generalized to other development environments such as RStudio or vsCode.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
@map0logo @ccordoba12 @juanis2112 thank you for submitting this lesson proposal. This is a very relevant topic for the community and the skills you describe would be very helpful for many researchers. You should all have received an invitation to join a Team within the `carpentries-incubator` organisation for developers/maintainers of this lesson. Once you have accepted the invitation, you can transfer the lesson repository into the Incubator.

After the transfer, the URL to your lesson will have changed and you will need to update the remotes in your local git repositories. Please also use the opportunity to rename the repository: we would like for all lessons in The Carpentries Incubator to have a repository name that describes the skills taught in the lesson, plus ideally the intended experience level of the audience and (if appropriate) the tool(s) taught as well. I would suggest `ide-novice-spyder` or similar?

Please post back here with a link to the repository when the transfer is complete, or with any questions if you have trouble with the invitations or the process.

**Comment by tobyhodges** [comment]
@map0logo now that the repository has been transferred to https://github.com/carpentries-incubator/ide-novice-spyder I will close this issue. I will still be notified if you post back here, so feel free to leave a comment below if you need help with anything while you continue to develop the lesson. You can also tag me in an issue on the lesson repository.

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member).

Lastly, you might consider opting in to list your lesson on [the Help Wanted page](https://carpentries.org/help-wanted-issues/) of The Carpentries website, which will automatically show any issues you add the `help-wanted` label to. This is a good way to attract contributions to your lesson from the wider community. At the moment, the best way to add your lesson to that page listing is by emailing me (tobyhodges at carpentries dot org), but we hope to have a more automated method set up soon.

**Comment by map0logo** [comment]
Hi Toby!

Thank you so much.

Roger!

**Comment by ccordoba12** [comment]
> You should all have received an invitation to join a Team within the carpentries-incubator organisation for developers/maintainers of this lesson

Thanks @tobyhodges for your help! I accepted the invitation a few days ago.
