### ISSUE TITLE
Machine Learning with Python and Scikit Learn

### ISSUE THREAD

**Issue by colinsauze** [carpentries-incubator/proposals#81]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Machine Learning with Python and Scikit Learn

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

yes, https://github.com/machinelearningcarpentry/machine-learning-novice

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

yes

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

add them later

8. Any other information you would like us to have or questions you have for us?

I'm debating what to make the exact title of this lesson. When I started it there weren't many other machine learning lessons, but now there's several and I think machine-learning-novice is perhaps too generic? 

I'm using a working title of "Machine Learning with Python and Scikit Learn" but am open to suggestions of something else.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks @colinsauze for proposing to transfer this lesson (mentioned previously in #19) into the Incubator. I have added you to a new Team in the `carpentries-incubator` organisation, and you should be able to transfer the repository into the organisation whenever you are ready. Regarding the title, it would indeed be good adjust the repository name when you make the transfer. Perhaps `machine-learning-novice-sklearn`? Or `machine-learning-novice-gapminder`, as I see you are using Gapminder life expectancy data in at least one of the episodes?

**Comment by colinsauze** [comment]
ok, i'll transfer it now. I think i'll go with machine-learning-novice-sklearn as I might move away from using gapminder data in future.

**Comment by tobyhodges** [comment]
Great thanks @colinsauze I can see the repository is now at https://github.com/carpentries-incubator/machine-learning-novice-sklearn

A few possible next steps for you: to keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). I guess you already know about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but feel free to ping me in an issue over on the lesson repository if you need help with anything.
