### ISSUE TITLE
Flight Data Management

### ISSUE THREAD

**Issue by jonititan** [carpentries-incubator/proposals#82]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
The analysis of flight data to detect features relevant to the continual improvement of safety.
I have been awarded funding to create lessons to support use of Matlab, Python, and Spark in the new [DARTeC](https://www.cranfield.ac.uk/centres/digital-aviation-research-and-technology-centre) computing environment.
I would like to make the introductory parts of that as open as possible as there is a deficit of engineering focused content in the carpentries currently.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Early examples of Python for FDM and engineering.  not a lesson at this stage.  
[Python for FDM](https://github.com/jonititan/FDM) 
[AircraftDesign](https://github.com/jonititan/AircraftDesign)

I will be focussing on the implementation of some of the identified precursors from WGB of [EOFDM](https://www.easa.europa.eu/domains/safety-management/safety-promotion/european-operators-flight-data-monitoring-eofdm-forum)  These will have the widest utility for industry and students.
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
yes.
4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
Yes and not yet but they will do

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
Yes but not quite yet.  I will develop it using the template and it can be transferred then.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for this lesson proposal, @jonititan. You should have received an invitation to join a Team for maintainers of this lesson in the `carpentries-incubator` organisation. 

Before I create the repository, I'd like to discuss the appropriate name for that repository with you: I like to try to capture something about the intended level of the audience, and maybe the tool(s) used to teach the lesson, in the repository name. For example, [the repository for the Software Carpentry Programming with Python lesson](https://github.com/swcarpentry/python-novice-inflammation) is called `python-novice-inflammation` because the lesson teaches Python, to novices, using an inflammation data set. Could we go for a similar approach here, e.g. `python-novice-flight-data`, `spark-novice-flight-data` or similar? 

Let me know your thoughts, and I can go ahead and set up the repository.

**Comment by jonititan** [comment]
How about 

[python-EOFDM-precursors](https://github.com/jonititan/python-EOFDM-precursors)

**Comment by tobyhodges** [comment]
Done! Your new lesson repository is at https://github.com/carpentries-incubator/python-EOFDM-precursors 🚀 

I have granted you Admin access to the repository so you have full control over it. You are also a Maintainer of that Team I made for maintainers opf the lesson - you don't need to do anything with it right now but it means you can add any collaborators to the Team in future, if you find others who want to help you develop/maintain the lesson.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). And you will learn all about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository if you need help.
