### ISSUE TITLE
Library Carpentry: Intro to Machine Learning and AI for Librarians and Archivists

### ISSUE THREAD

**Issue by noramcgregor** [carpentries-incubator/proposals#84]
Hey there! Our group will be incubating a new lesson for Library Carpentry "Introduction to Machine Learning for Librarians & Archivists".

Our objective with this Lesson is to empower GLAM staff to support, participate in and undertake in their own right, machine learning based research and projects with heritage collections. We envision creating an initial introductory lesson serving as a more generalised jumping off point for other more specific technology/data skill lessons. It would focus in the first instance on demystifying the basics of machine learning/AI through jargon busting, and present some hands-on practice, using cultural heritage datasets, based on current common applications of machine learning techniques in the sector today. 
 
At the end of this workshop, we expect Learners to be equipped to:
 
- Discuss and demonstrate ways in which machine learning is being innovatively used in the cultural heritage context today
- Be more familiar and conversant with some of the foundational concepts, terms, and tools of machine learning
- Consider ethical, transparency and fairness implications of applying machine learning to cultural heritage collections
- Understand the practical, technical steps behind incorporating machine learning applications in their own work
 
Though our group has complimentary skills and online teaching experience in this area we do not yet have materials prepared and will be using the study group to build the lesson from the ground up collaboratively.  Mike Trizna has begun work on a [potential framework](https://miketrizna.github.io/intro_to_ai_ml/) which we will use as our starting basis. 

- Nora McGregor, Digital Curator - British Library, UK
- Daniel van Strien, Digital Curator, Living with Machines, British Library, UK
- Mark Bell, Senior Digital Researcher, National Archives, UK 
- Mike Trizna, Data Scientist, Data Science Lab, Smithsonian Institute Lab, USA

**Comment by tobyhodges** [comment]
Hi @noramcgregor thanks for submitting this proposal. You, @MikeTrizna, and @davanstrien have all been invited to join a Team of maintainers for the lesson. You can add others to that Team too (you could start by adding Mark, as I do not know his GitHub username). That will grant them Maintain-level access to the repository, and you are Admin on the repository. 

The repository is here: https://github.com/carpentries-incubator/machine-learning-librarians-archivists

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). And you will learn all about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository if you need help.

**Comment by MikeTrizna** [comment]
Thanks for your approval and for setting up this new repo, @tobyhodges.

@noramcgregor, do you think you could go to the "machine-learning-librarians-maintainers" GitHub Team that was created, and add @mark-bell-tna? I think this link should take you there: https://github.com/orgs/carpentries-incubator/teams/machine-learning-librarians-maintainers/members

Also, can you change @davanstrien and me to "Maintainer" level? Right now, we are just listed as "Member" so we are unable to add new members.
