### ISSUE TITLE
LaTeX typesetting

### ISSUE THREAD

**Issue by baileythegreen** [carpentries-incubator/proposals#85]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Typesetting in LaTeX

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No, but I am working on it in one of the Carpentries Lesson Development Study Groups.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by edbennett** [comment]
While it is a little bit rough as I only delivered it once and I was not a trained Carpentries instructor at the time, I did use the Carpentries template and style to put together a LaTeX tutorial; it's at [here](https://edbennett.github.io/latex-tutorial/) ([repo](https://github.com/edbennett/latex-tutorial)). Feel free to take as much or as little of it (anywhere between "all" and "none") as you need!

**Comment by baileythegreen** [comment]
@edbennett Cool, thanks! I think you are not the only one to have made a Carpentries-esque LaTeX lesson, though the one I've seen before seemed to have a different focus from yours. Once there's a bit more movement on this (the first Study Groups meeting is tomorrow), you're welcome to contribute, if you'd like. There isn't exactly a repo yet, but I can point you to it, once there is.

**Comment by tobyhodges** [comment]
Hi @baileythegreen thank you for proposing the lesson, and @edbennett for sharing a link to your material on a similar topic (I will get to your proposal next!) I will be very interested to learn from this lesson when it is ready, and I'm sure it will be relevant to plenty of other members of the community as well.

Guessing that the lesson will be aimed at newcomers to LaTeX, I chose `latex-novice-typesetting` as the name of the repository, but feel free to change it if that is inaccurate. https://github.com/carpentries-incubator/latex-novice-typesetting

You should have received an invitation to join a Team of maintainers for the lesson. I will grant you access to add other members to that Team in the future, so you can include other collaborators if and when you need to. And you have full Admin access to the repository yourself too.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). And you will learn all about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository if you need help.
