### ISSUE TITLE
Data management and analytic pipelines for engineers

### ISSUE THREAD

**Issue by jonathanwheeler01** [carpentries-incubator/proposals#87]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

This is broad and needs refinement, but overall the focus of the lesson is to adapt existing Carpentry lessons and materials to address user stories and workflows using engineering data. Specifically, we have electric power consumption and solar irradiance data, and we'd like to craft a lesson focused on analysis and management of these data.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No.

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting this proposal, @jonathanwheeler01. I have created a repository for your lesson at https://github.com/carpentries-incubator/data-management-pipelines-engineering, and you should have received an invitation to join a Team of maintainers for this lesson (so far you are the only member but you will be able to add other collaborators to the lesson).

I chose a name for the repository based on your description above, but you have full Admin access so you can change the name and anything else you need to as you narrow down your idea of what the lesson will be about in the coming weeks.

You may already be aware of [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org) and [the Lesson Example](https://carpentries.github.io/lesson-example/), and you will have opportunities to read and discuss those resources in the coming weeks of the Lesson Development Study Groups program. For now, to keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member).

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository or message me on Slack if you need help.
