### ISSUE TITLE
java-novice-inflammation

### ISSUE THREAD

**Issue by annajiat** [carpentries-incubator/proposals#88]
1. What is the topic of your lesson or lesson proposal?
java-novice-inflammation

2. Do you already have a draft of your lesson?
No
Would like to follow
python-novice-inflammation

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
Jannetta Steyn [ @jsteyn ]

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting this proposal, @annajiat. I have created a repository for your lesson at https://github.com/carpentries-incubator/java-novice-inflammation, and you and @jsteyn should have received an invitation to join a Team of maintainers for this lesson.

You may already be aware of [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org) and [the Lesson Example](https://carpentries.github.io/lesson-example/), and you will have opportunities to read and discuss those resources in the coming weeks of the Lesson Development Study Groups program. For now, to keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member).

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository or message me on Slack if you need help.
