### ISSUE TITLE
Frictionless Data for Agriculture Research

### ISSUE THREAD

**Issue by richardostler** [carpentries-incubator/proposals#89]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Applying Frictionless Data for managing and sharing agricultural and agro-ecological research data. 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Some offline/intranet (Sharepoint) materials 

3. Do your materials conform to our [Code of Conduct][coc]?
Working as part of the Lesson Development Study Group, so a work in progress for now. 

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
No and No

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
Yes please

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
@richardostler

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting this proposal @richardostler! I have created the lesson repository for you at https://github.com/carpentries-incubator/frictionless-data-agriculture and you should have received an invitation to join a maintainer Team for the lesson. I have also granted you Admin level access to the repository so you have full control.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). And you will learn all about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository if you need help.
