### ISSUE TITLE
Make Software Citable

### ISSUE THREAD

**Issue by caifand** [carpentries-incubator/proposals#90]
Hi, I've had some conversations with @tobyhodges, and thanks for providing guidance. I want to suggest a lesson on software citation. I myself also have done some work in this area so far.

**1. What is the topic of your lesson or lesson proposal?**

Make Software Citable.

I have not decided on the lesson title yet. Currently I hope to include in this lesson:
1. What makes software citation matter
Reasons and motivations for software citation.
2. Where we are now in software citation
* Existing empirical studies that tell us how we are doing currently in terms of software citation
* Current information infrastructure that makes software citable.
3. How to make the software more citable
Practices to make software citable, including choosing between global standalone metadata format (e.g., `CodeMeta`, `.cff`) and domain specific metadata format (e.g., `R CITATION`) for software; providing visibility for text citation entry/software publication, etc.; and implications of one's software citation choices
Could include a checklist as well as tips and possible tools to make software citable.

**2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.**

I do not have templated lesson drafts yet. But I have some materials that can be drawn on.
My colleagues and I have a publication on a dataset we published for machine learning based software recognition in scholarly text. A copy of that publication can be [found in our dataset release](https://zenodo.org/record/4445202). It offers a quite comprehensive review of the existing initiatives by different stakeholders that aim to make software citable.
I also recently had [this work](https://arxiv.org/abs/2012.13117) coming out, in collaboration with software registries/repositories, for better software collection management practices. So can provide various perspectives on software citation.
And my colleagues and I have contributed to [citeas.org](url) so far, which is a search engine for discovering software online. 

There are some more work pieces from ours that can be useful for a lesson on this topic. But would be very happy to carve things out in conversation with the Carpentries community for a proper lesson :)

**3. Do your materials conform to our [Code of Conduct][coc]?**

Yes.

**4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).**

N/A

**5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?**

N/A

**6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.**

N/A

**7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.**

N/A

**8. Any other information you would like us to have or questions you have for us?**

I've skipped question 4-7 for now and will be happy to continue along these lines once I learn more about the proper practices in the Carpentries community.

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for this lesson proposal, @caifand! I have created a repository for the lesson at https://github.com/carpentries-incubator/citable-software, and you should also have received an invitation to join a Team for maintainers of that lesson. If you gain any collaborators on the lesson in the future, you will be able to add them to this team.

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). And you will learn all about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository if you need help.
