### ISSUE TITLE
Shell programming for workflow management

### ISSUE THREAD

**Issue by douglowe** [carpentries-incubator/proposals#92]
1. What is the topic of your lesson or lesson proposal?

Shell programming for workflow management. 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes, a beta(?) draft of the material: [https://github.com/UoMResearchIT/shell-programming-course.git](https://github.com/UoMResearchIT/shell-programming-course.git). 

3. Do your materials conform to our [Code of Conduct][coc]?

I believe so. Happy to get feedback and recommendations on what to change if it's not fully conforming.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes - see link in Q2.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

The material has been used as part of a course, and I'd like to leave the current version in it's current location for the students to continue referring to. But I'd like to fork a copy to the Incubator page.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

Myself (@douglowe) and @AnjaLeBlanc

8. Any other information you would like us to have or questions you have for us?

The intention is for this lesson to follow on from the shell introduction course. It's focused on workflow management (with an eye on working on HPC systems). It has a lot of the information that I think needs covering in the lessons (though we are also considering adding a lesson on awk, extending it to be covered as a one day lesson), but could certainly do with a lot more interactive challenges for the students (and more descriptive text needs adding, so it is more suitable for self-guided learning). 

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for this proposal @douglowe I have invited you and @AnjalLBlanc to join a Team of maintainers for this lesson. Once you have accepted that invitation, you should be able to transfer the repository into the carpentries-incubator organisation. 

Please post back here when you have done that, or if you have any questions/encounter some difficulty with the repository transfer.

**Comment by douglowe** [comment]
Hi @tobyhodges - thanks for adding us to the team. I've forked our repository here: [https://github.com/carpentries-incubator/shell-programming-course](https://github.com/carpentries-incubator/shell-programming-course).

cheers,
Doug

**Comment by tobyhodges** [comment]
Thanks @douglowe I will close this issue now, but I will still be notified if you post below, so please ping me again if you run into any trouble. You can also tag me on an issue in the lesson repository.

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member).

Lastly, you might consider opting in to list your lesson on [the Help Wanted page](https://carpentries.org/help-wanted-issues/) of The Carpentries website, which will automatically show any issues you add the `help-wanted` label to. This is a good way to attract contributions to your lesson from the wider community. At the moment, the best way to add your lesson to that page listing is by emailing me (tobyhodges at carpentries dot org), but we hope to have a more automated method set up soon.

**Comment by stain** [comment]
Does GitHub Pages need to be turned on for repository https://github.com/carpentries-incubator/shell-programming-course ? 

https://carpentries-incubator.github.io/shell-programming-course/ does not show up. I guess also list it on https://carpentries.org/community-lessons/
