### ISSUE TITLE
Statistical Inference for Biologists

### ISSUE THREAD

**Issue by kerchner** [carpentries-incubator/proposals#93]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Statistical Inference for Biologists

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

https://smcclatchy.github.io/statistical-inference-for-biology/ 

(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?

Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes / Yes

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

N/A

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Yes

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@smcclatchy
@kerchner

8. Any other information you would like us to have or questions you have for us?

We are currently working on this lesson within the framework of the Carpentries Lesson Development Study Groups.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks @kerchner and @smcclatchy for this lesson proposal. I have invited you both to join a Team for maintainers of this lesson. (I also mistakenly began creating a repository for the lesson before I remembered that you will transfer the repository in from Sue's account - please accept the invitation to join the Team, but ignore any invitations to a specific lesson repository.)

@smcclatchy once you have joined the Team, you should be able to initiate the repository transfer into the Incubator. Please post here when you have done that, so I can come and tie up a few loose ends. If you run into any difficulty with the transfer or would like any more information, please post here and I will try to help as soon as I can.

**Comment by smcclatchy** [comment]
@tobyhodges I have joined the maintainers team for this lesson.

**Comment by tobyhodges** [comment]
Thanks @smcclatchy you should now be able to transfer the repository to the `carpentries-incubator` organisation via the settings on your repository. You will remain Admin on the repository after that transfer is complete. Please give it a try and post back here if you have any questions about the process. Remember that you will need to update your remote URL on any local repositories you already have for the lesson.

**Comment by smcclatchy** [comment]
@tobyhodges I have some questions about viewing the published website. It's now at https://carpentries-incubator.github.io/statistical-inference-for-biology/, however my fork will not render as a website even with gh-pages turned on in settings. https://smcclatchy.github.io/statistical-inference-for-biology/
I have a DOI for my website referenced in a recent publication, so I need help making my fork live. [Nine quick tips for efficient bioinformatics curriculum development and training](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008007)

**Comment by tobyhodges** [comment]
@smcclatchy it looks like the page is live now? Perhaps GitHub needed some time to notice and get the site back online?

**Comment by tobyhodges** [comment]
It looks like everything is working alright with the repository @smcclatchy @kerchner so I am going to close this issue now. Please post back here or tag me in a new issue on your lesson repository if you are still having trouble.
