### ISSUE TITLE
Single-cell RNA sequencing (scRNA-seq)

### ISSUE THREAD

**Issue by BatoolMM** [carpentries-incubator/proposals#94]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Single-cell RNA sequencing (scRNA-seq)

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No. 

3. Do your materials conform to our [Code of Conduct][coc]?

Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template)

Yes, we used `styles` template to create the lesson [here](https://github.com/BatoolMM/scRNA-seq/tree/gh-pages) but there is hardly anything added to the lesson. 

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

Yes, We'd prefer to start a new repo in The Carpentries Incubator using the incubator-template rather than moving the ownership of this [one](https://github.com/BatoolMM/scRNA-seq/tree/gh-pages).

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

@BatoolMM
@ElnazAmanzadeh

8. Any other information you would like us to have or questions you have for us?

No, and sorry for the delay in opening the issue.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting this lesson proposal @BatoolMM @ElnazAmanzadeh you should both have received an invitation to join a Team of maintainers for the lesson. You should also have received invitations to join the lesson repository with Admin access https://github.com/carpentries-incubator/scrna-seq-analysis Please accept both invitations.

The README of that lesson repository includes a list of next steps for you to take, to finish getting set up in the Incubator. 

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers). And you will learn all about [the Curriculum Development Handbook](https://cdh.carpentries.org/), the [Lesson Example](https://carpentries.github.io/lesson-example/), and [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member) from your participation in the Study Groups program.

I will close this issue now that the repository is created, but I will still be notified if you post back here. You are also welcome to tag me in an issue on your lesson repository if you need help.

**Comment by BatoolMM** [comment]
Thank you Toby :)
