### ISSUE TITLE
Structural Neuroimaging Analysis in Python

### ISSUE THREAD

**Issue by nikhil153** [carpentries-incubator/proposals#96]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
Introduction to structural Neuroimaging Analysis in Python. 

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
Yes.
(If you answered "No" to question 2, you can skip the remaining questions. Thank you for your lesson idea!)

3. Do your materials conform to our [Code of Conduct][coc]?
Yes.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
No. 

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?
Yes.

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
Erin W Dickie: edickie

8. Any other information you would like us to have or questions you have for us?

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for this lesson proposal @nikhil153! Based on the people involved, am I correct to assume that this is intended to form part of the growing neuroimaging curriculum (along with https://github.com/carpentries-incubator/SDC-BIDS-IntroMRI, https://github.com/carpentries-incubator/SDC-EEGLAB, etc)? If so, would you like to suggest a name for the repository to stay consistent with the repositories that already exist here?

**Comment by nikhil153** [comment]
@tobyhodges yes, this course is structural counterpart of this [lesson](https://carpentries-incubator.github.io/SDC-BIDS-fMRI/). You can use this name for the repo: SDC-BIDS-sMRI. Thanks!

**Comment by tobyhodges** [comment]
Thanks @nikhil153 I have created the repository at https://github.com/carpentries-incubator/SDC-BIDS-sMRI and invited you and @edickie to join it with Admin access.

I will close this issue now that the repository has been created but feel free to post back here if you have any questions or need some help getting started. To keep in touch with The Carpentries curriculum community you may also find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3) (you will need to [first register for The Carpentries Slack](https://swc-slack-invite.herokuapp.com/) if you are not already a member).

Lastly, you might consider opting in to list your lesson on [the Help Wanted page](https://carpentries.org/help-wanted-issues/) of The Carpentries website, which will automatically show any issues you add the `help-wanted` label to. This is a good way to attract contributions to your lesson from the wider community. At the moment, the best way to add your lesson to that page listing is by emailing me (tobyhodges at carpentries dot org).
